#!/usr/bin/env python3
"""Erzeugt ui-de.json — Texte der Oberfläche und der Serverantworten, die (noch)
keine ST-ID aus dem Systemtext-Entwurf haben. Alle Einträge sind ENTWURF.
Aufruf: python3 shared/texts/build-ui.py"""
import json, os

T = {
  # ───── allgemeine Fehler und Hinweise ─────
  'UI-EINGABE-PRUEFEN': 'Bitte prüf deine Eingabe.',
  'UI-NICHT-VERFUEGBAR': 'Das ist nicht mehr verfügbar.',
  'UI-ZU-VIELE': 'Das waren gerade zu viele Versuche. Bitte warte einen Moment.',
  'UI-ZU-SPAET': 'Dafür ist es jetzt zu spät.',
  'UI-LINK-UNGUELTIG': 'Dieser Link ist nicht mehr gültig.',
  'UI-NEU-ANMELDEN': 'Bitte gib zur Sicherheit noch einmal dein Passwort oder einen Code ein.',
  'UI-TESTBETRIEB-EINLADUNG': 'Wir sind gerade im Testbetrieb. Zum Registrieren brauchst du einen Einladungscode.',
  'UI-TESTBETRIEB-HINWEIS': 'Testbetrieb — bitte nur erfundene Angaben und keine echten Fotos von dir.',
  'UI-WARTEFRIST': 'Die Wartefrist läuft noch.',
  'UI-DAUER-TAGE': '{tage} Tage',
  'UI-DAUER-GESPEICHERT': 'Gespeichert — gilt bis {zeit}.',

  # ───── Anmeldung, Codes ─────
  'UI-ANMELDUNG-FALSCH': 'Anmeldedaten stimmen nicht.',
  'UI-CODE-FALSCH': 'Der Code stimmt nicht.',
  'UI-CODE-NEU': 'Der Code ist abgelaufen. Lass dir einen neuen schicken.',
  'UI-CODE-WARTEN': 'Bitte warte kurz, bevor du einen neuen Code anforderst.',
  'UI-PASSWORT-KURZ': 'Das Passwort braucht mindestens {zahl} Zeichen.',
  'UI-NUMMER-UNGUELTIG': 'Diese Nummer können wir nicht verwenden.',
  'UI-APPLE-AUS': 'Anmelden mit Apple ist gerade nicht verfügbar.',
  'UI-EINWILLIGUNG-FEHLT': 'Bevor es weitergeht, brauchen wir deine Einwilligung.',
  'UI-EINWILLIGUNG-NEU': 'Der Text der Einwilligung hat sich geändert. Bitte lies ihn noch einmal.',
  'UI-SCHLUESSEL-FALSCH': 'Dieser Schlüssel passt nicht.',
  'UI-SCHLUESSEL-ABGELAUFEN': 'Das hat zu lange gedauert. Bitte versuch es noch einmal.',
  'UI-SCHLUESSEL-FEHLER': 'Der Schlüssel ließ sich nicht prüfen.',
  'UI-SCHLUESSEL-SYNC': 'Dieser Schlüssel wird mit anderen Geräten geteilt. Wir brauchen einen, der nur auf diesem Gerät liegt.',
  'UI-WHR-TITEL': 'Wiederherstellung deines Kontos',

  # ───── Konto- und Altersstatus ─────
  'UI-ALTER-UNTER-18': 'Bevor du weitermachen kannst, brauchen wir eine Altersprüfung.',
  'UI-PROFIL-FEHLT': 'Leg zuerst dein Profil an.',
  'UI-KONTO-EINGESCHRAENKT': 'Dein Konto ist eingeschränkt. Du kannst lesen, aber nichts senden.',
  'UI-KONTO-GESPERRT': 'Dein Konto ist gesperrt. In deinen Mitteilungen steht, warum — und wie du widersprechen kannst.',
  'UI-STUFE2-SCHON': 'Diese Prüfung hast du schon bestanden.',
  'UI-FOTOPRUEFUNG-EINWILLIGUNG': 'Für die Fotoprüfung brauchen wir deine ausdrückliche Zustimmung.',
  'UI-FOTOPRUEFUNG-FOTO': 'Wähl zuerst ein Foto aus deinem Profil.',
  'UI-FOTOPRUEFUNG-VERSUCHE': 'Du hast die Fotoprüfung heute schon oft versucht. Morgen geht es wieder.',

  # ───── Profil ─────
  'UI-NAME-UNGUELTIG': 'Der Name darf höchstens {max} Zeichen lang sein und keine Links oder Nummern enthalten.',
  'UI-MERKMALE-MAX': 'Du kannst höchstens {max} Merkmale wählen.',
  'UI-FOTOS-MAX': 'Mehr als acht Fotos gehen nicht.',
  'UI-SORT-AQ-AUS': 'Diese Sortierung gibt es nur, wenn deine eigene Antwortquote eingeschaltet ist.',
  'UI-KEIN-UNKENNTLICHES-FOTO': 'Du hast kein unkenntlich gemachtes Foto, das sich freischalten ließe.',

  # ───── Standort ─────
  'UI-ZONEN-MAX': 'Mehr als {max} Zonen gehen nicht.',
  'UI-ZONE-RADIUS': 'Der Radius muss zwischen {min} und {max} km liegen.',

  # ───── Gast ─────
  'UI-GAST-PAUSE': 'Die Vorschau ist für heute vorbei. Registrier dich, um weiterzumachen.',
  'UI-GAST-NETZ': 'Von diesem Netz aus wurde die Vorschau heute schon oft geöffnet.',

  # ───── Gespräche, Album ─────
  'UI-TREFFPUNKT-SPAETER': 'Das geht erst, wenn ihr beide geschrieben habt.',
  'UI-VERFALL-NICHT-DU': 'Nur wer das Verschwinden eingeschaltet hat, kann es ausschalten.',
  'UI-ALBUM-LEER': 'Dein Album ist noch leer.',
  'UI-ALBUM-MAX': 'Dein Album hat höchstens {max} Bilder.',
  'UI-ALBUM-NICHT-JETZT': 'Ein Album kannst du erst anbieten, wenn Bilder in diesem Gespräch erlaubt sind.',

  # ───── Melden, Entscheidungen, Widerspruch ─────
  'UI-MEL-INTIM': 'Intime Bilder ohne Einwilligung',
  'UI-MELDEN-INHALT-WEG': 'Dieser Inhalt ist nicht mehr da und lässt sich nicht mehr melden.',
  'UI-MELDEN-KONTAKT': 'Bitte gib einen Namen und eine E-Mail-Adresse an, damit wir dir antworten können.',
  'UI-MELDUNG-ENTSCHIEDEN': 'Deine Meldung {fallnummer}',
  'UI-DIE-PERSON': 'die Person',
  'UI-EINEN-INHALT': 'einen Inhalt von dir',
  'UI-DEIN-FOTO': 'dein Foto',
  'UI-DEIN-KONTO-EINGESCHRAENKT': 'dein Konto (du kannst lesen, aber nichts senden)',
  'UI-DEIN-KONTO-GESPERRT': 'dein Konto',
  'UI-ENTSCHEIDUNG-BLEIBT': 'kein Verstoß',
  'UI-ENTSCHEIDUNG-INHALT-ENTFERNT': 'Inhalt entfernt',
  'UI-ENTSCHEIDUNG-EINGESCHRAENKT': 'Konto eingeschränkt',
  'UI-ENTSCHEIDUNG-GESPERRT': 'Konto gesperrt',
  'UI-ENTSCHEIDUNG-AN-BEHOERDE': 'an die zuständige Behörde weitergegeben',
  'UI-ENTSCHEIDUNG-BETROFFEN': 'Eine Entscheidung zu deinem Konto',
  'UI-FOTO-ABGELEHNT-TITEL': 'Dein Foto wurde nicht freigegeben',
  'UI-WEGE-DAGEGEN': 'Du kannst innerhalb der Frist widersprechen. Ein anderer Mensch als der, der entschieden hat, prüft das. Außerdem steht dir die außergerichtliche Streitbeilegung und der Rechtsweg offen.',
  'UI-WIDERSPRUCH-LAEUFT': 'Zu dieser Entscheidung läuft schon ein Widerspruch.',
  'UI-WIDERSPRUCH-FRIST': 'Du kannst innerhalb von {stunden} Stunden widersprechen — unter „Ich“ → „Mitteilungen“.',
  'UI-WIDERSPRUCH-ENTSCHIEDEN': 'Dein Widerspruch {fallnummer}',
  'UI-WIDERSPRUCH-BLEIBT': 'Die Entscheidung bleibt bestehen.',
  'UI-WIDERSPRUCH-AUFGEHOBEN': 'Die Entscheidung ist aufgehoben. Alles ist wiederhergestellt.',
  'UI-WIDERSPRUCH-ABGEMILDERT': 'Die Entscheidung ist abgemildert.',
  'UI-WIDERSPRUCH-OFFENLEGUNG': 'Hinweis: Die Person, die über deinen Widerspruch entschieden hat, hat die ursprüngliche Entscheidung mit freigegeben. Wir sind zurzeit nur zu zweit.',
  'UI-WIDERSPRUCH-HASH-WEG': 'Zu dieser Entscheidung können wir keine Einzelheiten nennen. Der Weg dagegen führt über die zuständige Behörde.',
  'UI-SPERRE-TITEL': 'Eine Entscheidung zu deinem Konto',
  'UI-SPERRE-AB': 'Gilt ab: {zeit}',
  'UI-SPERRE-LOESCHUNG': 'Nach Ablauf aller Fristen wird das Konto gelöscht.',
  'UI-SPERRE-AUFGEHOBEN-TITEL': 'Dein Konto ist wieder frei',
  'UI-SPERRE-AUFGEHOBEN-TEXT': 'Die Einschränkung deines Kontos ist aufgehoben. Du kannst alles wieder wie vorher nutzen.',

  # ───── Check-in ─────
  'UI-CHECKIN-FRAGE-TEXT': 'Alles in Ordnung? Tipp auf „Mir geht’s gut“.',
  'UI-CHECKIN-MAIL-BETREFF': 'Nachricht',
  'UI-CHECKIN-WEITERREICHEN': 'Bitte öffnen',
  'UI-CHECKIN-ZEIT': 'Der Beginn muss zwischen jetzt und den nächsten 24 Stunden liegen.',

  # ───── Ereignisse ─────
  'UI-EREIGNIS-ABGESAGT': 'Diese Veranstaltung ist abgesagt.',
  'UI-EREIGNIS-VORBEI': 'Diese Veranstaltung ist vorbei.',

  # ───── Datenkonto ─────
  'UI-EXPORT-FEHLER': 'Deine Datenkopie ließ sich nicht erstellen. Bitte fordere sie noch einmal an.',
  'UI-RUECKMELDUNG-ANTWORT': 'Antwort auf deine Rückmeldung',

  # ───── Mails (Betreff und erster Satz ohne Anlass und ohne Produktnamen) ─────
  'UI-MAIL-HILFE-EINGANG': 'Wir haben deine Nachricht unter der Fallnummer {fallnummer} erhalten. Ein Mensch liest sie und antwortet dir an diese Adresse.',
  'UI-MAIL-MELDUNG-EINGANG': 'Wir haben deine Nachricht unter der Fallnummer {fallnummer} erhalten. Wir melden uns, sobald entschieden ist.',
  'UI-MAIL-KOPF-EINGANG': 'Deine Nachricht ist angekommen',
  'UI-MAIL-KOPF-ANTWORT': 'Unsere Antwort',
  'UI-MAIL-KOPF-ENTSCHEIDUNG': 'Wir haben entschieden',
  'UI-MAIL-KOPF-ADRESSE': 'Adresse bestätigen',
  'UI-MAIL-WHR-ABBRECHEN': 'Das war ich nicht — abbrechen',
  'UI-MAIL-ANTWORT-EINLEITUNG': 'Hier ist unsere Antwort zu deinem Fall {fallnummer}.',
  'UI-MAIL-ORT-BETREFF': 'Vorgang {nummer}',
  'UI-MAIL-ORT-TEXT': 'Bitte bestätige deine Adresse mit diesem Link: {link}\n\nDanach prüft ein Mensch die Anfrage {nummer}, in der Regel innerhalb von 24 Stunden. Wenn du nichts angefragt hast, ignoriere diese Mail.',
  'UI-MAIL-ORT-BESTAETIGT': 'Deine Anfrage {nummer} ist bestätigt. Der Eintrag trägt jetzt das Kennzeichen „vom Ort bestätigt“.',
  'UI-MAIL-ORT-ENTFERNT': 'Deine Anfrage {nummer} ist bestätigt. Der Eintrag ist entfernt und wird nicht wieder aufgenommen.',
  'UI-MAIL-ORT-ABGELEHNT': 'Deine Anfrage {nummer} konnten wir nicht bestätigen. Grund: {grund}',
  'UI-MAIL-ORT-RUECKFRAGE': 'Zu deiner Anfrage {nummer} haben wir eine Rückfrage:\n\n{frage}\n\nAntworte einfach auf diese Mail.',
  'UI-MAIL-TERMIN-BETREFF': 'Deine Einreichung',

  # ───── Moderationswerkzeug ─────
  'UI-MOD-ANMELDEN': 'Bitte melde dich an.',
  'UI-MOD-RECHT': 'Dafür hat deine Rolle keine Berechtigung.',
  'UI-AUSWEIS-TITEL': 'Altersprüfung',
  'UI-AUSWEIS-WARUM': 'Hier dürfen nur Volljährige sein. Wir lesen auf dem Foto deines Ausweises nur das Geburtsdatum — auf unserem eigenen Server, ohne andere Firmen. Gespeichert wird nur „geprüft ja/nein“, der Zeitpunkt und der Weg.',
  'UI-AUSWEIS-LAEUFT': 'Dein Ausweis liegt gerade bei uns zur Prüfung. Du bekommst eine Mitteilung, sobald wir fertig sind.',
  'UI-AUSWEIS-OK': 'Dein Alter ist bestätigt. Die Bilder deines Ausweises haben wir gelöscht.',
  'UI-AUSWEIS-UNLESBAR': 'Wir konnten das Geburtsdatum auf deinem Ausweis nicht sicher lesen. Die Bilder haben wir gelöscht. Bitte versuch es noch einmal — gut ausgeleuchtet, ohne Spiegelung.',
  'UI-AUSWEIS-NOCHMAL': 'Wir konnten auf dem Foto kein Geburtsdatum finden. Bitte fotografiere den Ausweis noch einmal: ganz im Bild, scharf, ohne Spiegelung.',
  'UI-AUSWEIS-PRUEFUNG': 'Ein Mensch aus unserem Team schaut sich das Geburtsdatum an — meist innerhalb von {stunden} Stunden. Du bekommst eine Mitteilung. Danach löschen wir die Bilder.',
  'UI-AUSWEIS-WEG': 'Mit einem Foto deines Ausweises',
  'UI-AUSWEIS-UEBERSCHRIFT': 'Ausweis fotografieren',
  'UI-AUSWEIS-ERKL': 'Wir schauen nur auf dein Geburtsdatum. Name, Foto, Adresse und Ausweisnummer darfst du abdecken — wir brauchen sie nicht und speichern sie nicht.',
  'UI-AUSWEIS-ERKL-2': 'Ist das Datum sicher lesbar, bist du sofort fertig und wir behalten kein Bild. Sonst prüft ein Mensch aus unserem Team und löscht die Bilder danach.',
  'UI-AUSWEIS-VORNE': 'Vorderseite (mit Geburtsdatum)',
  'UI-AUSWEIS-HINTEN': 'Rückseite (freiwillig — die drei Zeilen unten helfen beim Lesen)',
  'UI-AUSWEIS-SENDEN': 'Prüfen',
  'UI-AUSWEIS-LAEUFT-JETZT': 'Wir lesen das Datum …',
  'UI-UPDATE-UNBEKANNT': 'Diese Version gibt es nicht als Release.',
  'UI-UPDATE-SCHON': 'Diese Version ist schon installiert.',
  'UI-UPDATE-LAEUFT': 'Es läuft schon eine Aktualisierung.',
  'UI-UPDATE-KEIN-UPDATER': 'Der Dienst „updater“ antwortet nicht. Läuft er? (docker compose ps)',
  'UI-TEAM-LETZTER-OWNER': 'Es muss immer mindestens ein aktiver Owner bleiben.',
  'UI-TEAM-KENNUNG-VERGEBEN': 'Diese Kennung ist schon vergeben.',
  'UI-TEAM-NICHT-SELBST': 'Den eigenen Zugang kannst du hier nicht sperren oder löschen.',
  'UI-TEAM-PASSWORT-GLEICH': 'Das neue Passwort muss sich vom alten unterscheiden.',
  'UI-MOD-GRUND': 'Ohne Begründung wird nichts ausgeführt.',
  'UI-MOD-ZWEITE-PERSON': 'Dafür braucht es die Freigabe einer zweiten Person.',
  'UI-MOD-EIGENER-ANTRAG': 'Den eigenen Antrag kann niemand selbst freigeben.',
  'UI-MOD-EIGENER-FALL': 'Über die eigene Entscheidung entscheidet eine andere Person.',
  'UI-MOD-NACH-21': 'Ab 21 Uhr werden keine Hash-Fälle mehr geöffnet. Die Frist lässt das zu.',
  'UI-MOD-TAGESGRENZE': 'Heute sind es schon zwei Hash-Fälle. Übergib den Fall an die zweite Person oder an die Beschwerdestelle.',
  'UI-MOD-SCHON-ENTSCHIEDEN': 'Dieser Fall ist schon entschieden.',
  'UI-MOD-KEIN-KONTO': 'Zu diesem Fall gibt es kein Konto (mehr).',
  'UI-MOD-BEZUG-FEHLT': 'Ohne gültige Fall- oder Meldenummer geht das nicht.',
  'UI-MOD-ANTRAG-OFFEN': 'Zu diesem Konto ist schon ein Antrag offen.',
  'UI-MOD-NEUER-GRUND': 'Mit genau diesem Grund wurde schon einmal abgelehnt. Ein neuer Anlauf braucht einen neuen Grund.',
  'UI-MOD-NICHTS-AUFZUHEBEN': 'Dieses Konto ist weder eingeschränkt noch gesperrt.',
  'UI-MOD-HASH-WIDERSPRUCH': 'Einen Hash-Fall entscheidet nicht das Werkzeug, sondern die Behörde.',
  'UI-MOD-KATEGORIE-WIDERSPRUCH': 'Kategorie 7 ist kein Vorgang, sondern ein Widerspruch.',
  'UI-MOD-ERST-RUECKFRAGE': 'Für diesen Ort gibt es mehrere Anfragen. Erst Rückfrage bei allen stellen.',
  'UI-MOD-PRUEFLISTE': 'Ohne alle fünf Prüfpunkte keine Freigabe.',
  'UI-MOD-ORT-GESPERRT': 'Dieser Ort wurde auf eigenen Wunsch entfernt und wird nicht wieder aufgenommen.',
  'UI-MOD-ENTWURF-VORHANDEN': 'Zu diesem Fall gibt es schon einen Entwurf.',
  'UI-MOD-TEXT-BESTAETIGEN': 'Der Sachverhalt muss gelesen und bestätigt sein.',
  'UI-MOD-PARAMETER-TYP': 'Dieser Wert passt nicht zum Parameter.',
  'UI-MOD-ANSPRECHPERSON-FEHLT': 'Ohne hinterlegte Ansprechperson lässt sich der Hash-Abgleich nicht einschalten.',
  'UI-MOD-ABGLEICH-FEHLT': 'Es ist kein Abgleichdienst angebunden (HASH_PROVIDER).',
  'UI-MOD-AUS-VORGANG': 'Aus dem Vorgang {nummer} des Kontaktservice.',
  'UI-MOD-NOTFALL-1': 'Ärztlicher Bereitschaftsdienst: 116117',
  'UI-MOD-NOTFALL-2': 'TelefonSeelsorge: 0800 111 0 111 und 0800 111 0 222',

  # ───── Hilfe: Kategorien (kontaktservice-und-tickets.md 2.3) ─────
  'UI-HLF-KAT-1': 'Jemand ist in Gefahr',
  'UI-HLF-KAT-2': 'Belästigung, Drohung, verbotener Inhalt',
  'UI-HLF-KAT-3': 'Ich komme nicht in mein Konto',
  'UI-HLF-KAT-4': 'Zahlung und Abo',
  'UI-HLF-KAT-5': 'Etwas funktioniert nicht',
  'UI-HLF-KAT-6': 'Meine Daten — Auskunft, Löschung, Export, Widerspruch',
  'UI-HLF-KAT-7': 'Mein Konto wurde eingeschränkt',
  'UI-HLF-KAT-8': 'Ein Ort oder eine Veranstaltung',
  'UI-HLF-KAT-9': 'Presse, Behörde, rechtliche Anfrage',
  'UI-HLF-KAT-10': 'Etwas anderes',
}


# ───── App-Oberfläche (Beschriftungen ohne eigene ST-ID) ─────
APP = {
  'UI-APP-ZURUECK': 'Zurück', 'UI-APP-SCHLIESSEN': 'Schließen', 'UI-APP-MENUE': 'Menü', 'UI-APP-MEHR': 'Mehr',
  'UI-APP-SPEICHERN': 'Speichern', 'UI-APP-SPEICHERN-DATEI': 'Als Datei speichern', 'UI-APP-SENDEN': 'Senden',
  'UI-APP-LOESCHEN': 'Löschen', 'UI-APP-KOPIEREN': 'Kopieren', 'UI-APP-LAEDT': 'Lädt …', 'UI-APP-NICHT-JETZT': 'Nicht jetzt',
  'UI-APP-SPAETER': 'Später', 'UI-APP-ERLEDIGT': 'erledigt', 'UI-APP-OFFEN': 'offen', 'UI-APP-GEPRUEFT': 'geprüft',
  'UI-APP-PROFIL': 'Profil', 'UI-APP-HAUPTNAVIGATION': 'Hauptnavigation', 'UI-APP-NEU': '{zahl} neu', 'UI-UND': 'und',
  'UI-SCHRITT': '{n} von {von}',
  'UI-TAB-NAEHE': 'Nähe', 'UI-TAB-CHATS': 'Chats', 'UI-TAB-ICH': 'Ich',

  'UI-GAST-STADT': 'Oder wähl eine Stadt:',
  'UI-KONTO-ANMELDEN': 'Anmelden', 'UI-KONTO-EINLADUNG': 'Einladungscode', 'UI-KONTO-EMAIL': 'E-Mail-Adresse',
  'UI-KONTO-EMAIL-ODER-NUMMER': 'E-Mail-Adresse oder Telefonnummer', 'UI-KONTO-NUMMER': 'Telefonnummer', 'UI-KONTO-PASSWORT': 'Passwort',
  'UI-KONTO-PASSWORT-NEU': 'Neues Passwort', 'UI-KONTO-PASSWORT-ALT': 'Bisheriges Passwort', 'UI-KONTO-PASSWORT-AENDERN': 'Passwort ändern',
  'UI-KONTO-PASSWORT-GEAENDERT': 'Passwort geändert. Andere Geräte sind abgemeldet.',
  'UI-KONTO-ANZEIGEN': 'Zeigen', 'UI-KONTO-VERBERGEN': 'Verbergen', 'UI-KONTO-VERGESSEN': 'Passwort vergessen',
  'UI-KONTO-VERGESSEN-GESENDET': 'Wenn es ein Konto mit dieser Angabe gibt, haben wir dir einen Link oder Code geschickt.',
  'UI-KONTO-LINK-SENDEN': 'Link schicken', 'UI-KONTO-WIEDERHERSTELLEN': 'Konto wiederherstellen',
  'UI-KONTO-WARUM-NICHT-GOOGLE': 'Warum nicht Google oder Facebook?', 'UI-KONTO-CODE': 'Code', 'UI-KONTO-CODE-GESENDET': 'Wir haben dir einen Code geschickt. Gib ihn hier ein.',
  'UI-KONTO-GERAETECODE': 'Neues Gerät: Wir haben dir einen Code per SMS geschickt.', 'UI-KONTO-NEU-SENDEN': 'Code nicht bekommen? Neu senden',
  'UI-KONTO-NEU-SENDEN-IN': 'Neu senden in {s} Sekunden', 'UI-KONTO-SCHON-KONTO': 'Ich habe schon ein Konto', 'UI-KONTO-NOCH-KEINS': 'Noch kein Konto? Konto anlegen',
  'UI-KONTO-CODE-SENDEN': 'Code schicken', 'UI-KONTO-SICHERN': 'Zugang sichern', 'UI-KONTO-SICHERN-ERKL': 'Wiederherstellungscode, zweiter Weg, Vertrauenspersonen, Passwort',

  'UI-EINW-TITEL': 'Bevor wir etwas speichern', 'UI-EINW-KONTROLLE': 'Ich willige ein.', 'UI-EINW-NICHT': 'Nicht einwilligen',
  'UI-EINW-ABGELEHNT': 'Ohne Einwilligung ist kein Konto möglich. Wir haben deine Anmeldedaten gelöscht.',
  'UI-WHR-CODE-TITEL': 'Wiederherstellungscode', 'UI-WHR-GESICHERT': 'Ich habe den Code gesichert.', 'UI-WHR-JA': 'Ja, habe ich',
  'UI-WHR-NEU-ZEIGEN': 'Neuen Code zeigen', 'UI-WHR-NEU-ERZEUGEN': 'Neuen Code erzeugen', 'UI-WHR-MIT-CODE': 'Mit meinem Wiederherstellungscode',
  'UI-WHR-MIT-SCHLUESSEL': 'Mit dem Schlüssel einer Vertrauensperson', 'UI-WHR-SCHLUESSEL': 'Schlüssel der Vertrauensperson',
  'UI-WHR-WARTET': 'Wiederherstellung läuft. Aus Sicherheitsgründen geht es erst ab {datum} weiter. Bis dahin kann sie abgebrochen werden.',
  'UI-WHR-BEREIT': 'Die Wartefrist ist vorbei. Leg jetzt ein neues Passwort fest.', 'UI-WHR-BEENDET': 'Diese Wiederherstellung ist beendet.',
  'UI-WHR-DAS-WAR-ICH-NICHT': 'Das war ich nicht', 'UI-WHR-ABGEBROCHEN': 'Die Wiederherstellung ist abgebrochen.',
  'UI-WHR-ZWEITER-WEG': 'Zweiter Weg', 'UI-WHR-VERTRAUEN': 'Vertrauenspersonen', 'UI-WHR-SCHLUESSEL-ERZEUGEN': 'Schlüssel erzeugen',
  'UI-WHR-SCHLUESSEL-NEU': 'Neuen Schlüssel erzeugen (der alte gilt dann nicht mehr)', 'UI-WHR-SCHLUESSEL-ENTFERNEN': 'Schlüssel ungültig machen',
  'UI-WHR-SCHLUESSEL-WEITERGEBEN': 'Gib diesen Schlüssel einer Person, der du vertraust. Er wird nur jetzt angezeigt.',

  'UI-PROFIL-NAME': 'Name', 'UI-PROFIL-FARBE': 'Farbe der Initiale', 'UI-PROFIL-WEG': 'Dieses Profil gibt es nicht mehr.',
  'UI-PROFIL-SCHREIBEN': 'Schreiben', 'UI-PROFIL-NICHT-MERKEN': 'Nicht mehr merken', 'UI-PROFIL-DU': 'Das bist du',
  'UI-PROFIL-SO-SEHEN-DICH': 'So sehen dich andere', 'UI-PROFIL-BEARBEITEN': 'Bearbeiten', 'UI-PROFIL-ANSEHEN': 'Ansehen',
  'UI-PROFIL-ALTERSPRUEFUNG': 'Altersprüfung', 'UI-PROFIL-FOTOS': 'Fotos', 'UI-PROFIL-ALTER': 'Alter (freiwillig)',
  'UI-PROFIL-ALTER-ERKL': 'Nur die Zahl, kein Geburtsdatum.', 'UI-PROFIL-INTERESSEN': 'Interessen', 'UI-PROFIL-FREITEXT': 'Über mich',
  'UI-PROFIL-EIGENE-BESCHREIBUNG': 'Eigene Beschreibung', 'UI-PROFIL-ALLE-WENN-LEER': 'Nichts gewählt heißt: alle.',
  'UI-PROFIL-ANTWORTQUOTE': 'Antwortquote zeigen', 'UI-PROFIL-FOTO-VON': '{n} von {von}', 'UI-PROFIL-FOTO-ZURUECK': 'Voriges Foto', 'UI-PROFIL-FOTO-WEITER': 'Nächstes Foto',
  'UI-ALTER-NOCH-AKTUELL': 'Stimmt dein Alter noch? Bei dir steht {alter}.', 'UI-ALTER-STIMMT': 'Stimmt', 'UI-ALTER-AENDERN': 'Ändern',

  'UI-FOTO-HINZU': 'Foto hinzufügen', 'UI-FOTO-HOCHLADEN': 'Hochladen', 'UI-FOTO-ANDERES': 'Anderes Foto', 'UI-FOTO-SICHTBAR': 'Sichtbar',
  'UI-FOTO-EINSPRUCH': 'Einspruch einlegen', 'UI-FOTO-EINSPRUCH-TEXT': 'Warum sollte das Foto doch gezeigt werden?',
  'UI-FOTO-NACH-VORNE': 'Nach vorne', 'UI-FOTO-NACH-HINTEN': 'Nach hinten', 'UI-FOTO-ZEIGEN': 'Fotos im Profil zeigen',
  'UI-FOTO-ZUSCHNITT': 'Zuschnitt', 'UI-FOTO-LINKS': 'Nach links', 'UI-FOTO-RECHTS': 'Nach rechts', 'UI-FOTO-HOCH': 'Nach oben', 'UI-FOTO-RUNTER': 'Nach unten',
  'UI-FOTOPRUEFUNG-EINWILLIGUNG-TEXT': 'Ich willige ein, dass mein Selfie mit meinen Profilfotos verglichen wird. Das Selfie wird danach gelöscht.',

  'UI-NAEHE-SORTIERT': 'Sortiert nach: {sortierung}', 'UI-NAEHE-STAND': 'Stand: {uhrzeit}', 'UI-NAEHE-WOCHENAKTIVE': 'Diese Woche aktiv',
  'UI-NAEHE-STADT-WAEHLEN': 'Stadt wählen',
  'UI-SORT-TITEL': 'Sortieren nach', 'UI-SORT-NAEHE': 'Nähe', 'UI-SORT-NAEHE-ERKL': 'Nach Entfernungsstufe, innerhalb der Stufe nach Aktivität, dann zufällig.',
  'UI-SORT-ANTWORTQUOTE': 'Antwortquote', 'UI-SORT-ANTWORTQUOTE-ERKL': 'Wer oft auf erste Nachrichten antwortet, steht weiter oben.',
  'UI-SORT-NEU': 'Neu hier', 'UI-SORT-NEU-ERKL': 'Wer neu ist, steht zuerst.', 'UI-SORT-ABSICHT': 'Passende Absicht', 'UI-SORT-ABSICHT-ERKL': 'Wer gerade dasselbe sucht wie du, steht zuerst.',
  'UI-FILTER': 'Filter', 'UI-FILTER-HOECHSTENS-ZWEI': 'Höchstens zwei gleichzeitig.', 'UI-FILTER-ENTFERNUNG': 'Entfernung', 'UI-FILTER-ABSICHT': 'Absicht',
  'UI-FILTER-ALTER': 'Alter', 'UI-FILTER-ALTER-AN': 'Nach Alter filtern', 'UI-FILTER-VON': 'von', 'UI-FILTER-BIS': 'bis',
  'UI-FILTER-TREFFER': '{zahl} Profile', 'UI-FILTER-ANZEIGEN': 'Anzeigen', 'UI-FILTER-ALLE-ENTFERNEN': 'Alle Filter entfernen', 'UI-FILTER-ENTFERNEN': 'Filter entfernen',
  'UI-ABSICHT-ERNEUERN': '„{absicht}“ erneuern',
  'UI-STUFE-GROB': 'ungefähr', 'UI-STUFE-GROB-ERKL': 'Gerundet auf etwa 2 km. Voreinstellung.', 'UI-STUFE-NAH': 'genauer',
  'UI-STUFE-NAH-ERKL': 'Gerundet auf etwa 500 m.', 'UI-STUFE-AUS': 'aus', 'UI-STUFE-AUS-ERKL': 'Kein Standort. Du erscheinst nicht im Raster und nicht auf der Karte.',
  'UI-STANDORT-ANDERE-SEHEN': 'Andere sehen nur: unter 1 km · 1–3 km · 3–10 km · über 10 km.',
  'UI-STANDORT-STADT': 'Stadt ohne Standort', 'UI-STANDORT-STADT-ERKL': 'Ohne Standort zeigen wir Profile aus dieser Stadt — ohne Entfernungen.',
  'UI-ZONE': 'Zone', 'UI-ZONE-ANLEGEN': 'Zone anlegen', 'UI-ZONE-HIER': 'Mittelpunkt: mein jetziger Ort', 'UI-ZONE-MITTE-ERKL': 'Die Mitte wird nur als Rasterzelle gespeichert, verschlüsselt.',
  'UI-ZONE-MITTE-GESETZT': 'Mittelpunkt gesetzt.', 'UI-ZONE-RADIUS-LABEL': 'Radius: {km} km', 'UI-ZONE-ERSATZPUNKT': 'Ersatzpunkt', 'UI-ZONE-UNSICHTBAR': 'Unsichtbar',
  'UI-ZONE-ERSATZ-ABSTAND': 'Ersatzpunkt etwa {km} km von der Mitte', 'UI-ZONE-ANDERER-PUNKT': 'Anderer Punkt', 'UI-ZONE-NAME': 'Name der Zone (freiwillig)',
  'UI-ZONE-GERADE-ERSATZ': 'Du bist gerade in einer Zone: andere sehen den Ersatzpunkt.', 'UI-ZONE-GERADE-UNSICHTBAR': 'Du bist gerade in einer Zone und unsichtbar.',

  'UI-CHATS-ARCHIV': 'Archiv', 'UI-CHATS-WAS-SIND-ANFRAGEN': 'Was sind Anfragen?', 'UI-CHATS-ZUM-RASTER': 'Zum Raster', 'UI-CHATS-NICHT-MEHR-DA': 'Profil nicht mehr verfügbar',
  'UI-CHAT-BILD': 'Bild', 'UI-CHAT-ORT': 'Treffpunkt', 'UI-CHAT-ALBUM': 'Privates Album', 'UI-CHAT-DU': 'Du', 'UI-CHAT-NACHRICHT': 'Nachricht',
  'UI-CHAT-SENDEN': 'Senden', 'UI-CHAT-BILD-SENDEN': 'Bild senden', 'UI-CHAT-ZULASSEN': 'Zulassen', 'UI-CHAT-ABLEHNEN': 'Ablehnen',
  'UI-CHAT-VERFALL-AUS': 'Verschwindende Nachrichten ausschalten', 'UI-CHAT-GESICHT-AUS': 'Gesicht wieder unkenntlich', 'UI-CHAT-ALBUM-TEILEN': 'Privates Album teilen',
  'UI-CHAT-VERSCHWINDET': 'verschwindet', 'UI-EIS-TITEL': 'Ein Einstieg', 'UI-EIS-ANDERE': 'Andere Vorschläge',
  'UI-SYS-VERFALL-AN': '{name} hat verschwindende Nachrichten eingeschaltet.', 'UI-SYS-VERFALL-AUS': '{name} hat verschwindende Nachrichten ausgeschaltet.',
  'UI-SYS-GESICHT-AN': '{name} zeigt das Gesicht in diesem Gespräch.', 'UI-SYS-GESICHT-AUS': '{name} zeigt das Gesicht wieder unkenntlich.',
  'UI-SYS-WIEDER-GEOEFFNET': '{name} hat das Gespräch wieder geöffnet.', 'UI-SYS-': '',
  'UI-ALBUM-TITEL': 'Privates Album', 'UI-ALBUM-MEINS': 'Mein privates Album', 'UI-ALBUM-HINZU': 'Bild hinzufügen', 'UI-ALBUM-FREIGABEN': 'Freigaben',
  'UI-ALBUM-ANGEBOTEN': 'Album angeboten', 'UI-ALBUM-OEFFNEN': 'Album öffnen', 'UI-ALBUM-NICHT-MEHR-ZEIGEN': 'Nicht mehr zeigen', 'UI-ALBUM-BEENDET': 'Freigabe beendet — wirkt nur nach vorn.',
  'UI-ALBUM-STATUS-OFFERED': 'wartet auf Antwort', 'UI-ALBUM-STATUS-ACCEPTED': 'angenommen', 'UI-ALBUM-STATUS-DECLINED': 'abgelehnt', 'UI-ALBUM-STATUS-ENDED': 'beendet', 'UI-ALBUM-STATUS-GESCHLOSSEN': 'geschlossen',
  'UI-MELDEN-AUSWAHL': 'Welche Nachrichten oder Bilder?', 'UI-MELDUNGEN-TITEL': 'Meine Meldungen', 'UI-MELDUNGEN-BETRIFFT-DICH': 'Entscheidungen, die dich betreffen',
  'UI-MELDUNGEN-EIGENE': 'Deine Meldungen', 'UI-MELDUNGEN-LEER': 'Du hast noch nichts gemeldet.', 'UI-MELDUNGEN-WIDERSPRUECHE': 'Einsprüche und Widersprüche',
  'UI-WIDERSPRUCH-TEXT': 'Was sollen wir noch einmal prüfen?', 'UI-WIDERSPRUCH-FRIST-BIS': 'Antwort bis {datum}',
  'UI-MEL-CSAM': 'Darstellung von sexuellem Kindesmissbrauch',

  'UI-PRUEFUNG-WARUM': 'Warum?', 'UI-PRUEFUNG-STARTEN': 'Prüfung starten', 'UI-PRUEFUNG-LAEUFT': 'Die Prüfung läuft noch …',
  'UI-PRUEFUNG-NACHRICHT-SENDEN': 'Weiter zur Nachricht', 'UI-PRUEFUNG-ATTRAPPE': 'Testbetrieb: Es ist noch kein Prüfpartner angebunden. Die Prüfung wird nur nachgestellt.',
  'UI-STUFE2-SCHLUESSEL': 'Bestätige dich jetzt mit einem Schlüssel, der nur auf diesem Gerät liegt (Fingerabdruck, Gesicht oder Geräte-PIN).',
  'UI-STUFE2-BESTAETIGEN': 'Mit dem Gerät bestätigen', 'UI-STUFE2-NICHT-MOEGLICH': 'Dieser Browser kann keinen gerätegebundenen Schlüssel anlegen.',

  'UI-HEUTE-KARTE': 'Karte', 'UI-HEUTE-LISTE': 'Liste', 'UI-HEUTE-JETZT': 'Jetzt und heute Abend', 'UI-HEUTE-OFFEN': 'Orte, die heute geöffnet haben',
  'UI-HEUTE-WOCHE': 'Diese Woche', 'UI-HEUTE-DU': 'Du (ungefähr)', 'UI-HEUTE-SCHEMATISCH': 'Schematische Karte, etwa {km} km um dich. Personen nur als grobe Gruppe.',
  'UI-ORT-BESTAETIGT': 'vom Ort bestätigt', 'UI-ORT-WERKZEUGKONTO': 'Eintrag über ein Werkzeugkonto des Ortes', 'UI-ORT-OEFFNUNGSZEITEN': 'Öffnungszeiten',
  'UI-ORT-GESCHLOSSEN': 'geschlossen', 'UI-ORT-ZEITEN-UNBEKANNT': 'Öffnungszeiten unbekannt', 'UI-ORT-HEUTE-OFFEN': 'Heute geöffnet: {zeiten}',
  'UI-ORT-HEUTE-OFFEN-KURZ': 'heute geöffnet', 'UI-ORT-HEUTE-ZU': 'Heute geschlossen', 'UI-ORT-NAECHSTES': 'Als Nächstes: {titel}, {zeit}',
  'UI-ORT-EREIGNISSE': 'Kommende Ereignisse', 'UI-ORT-ADRESSE': 'Adresse', 'UI-ORT-KARTEN-APP': 'In Karten-App öffnen',
  'UI-ORT-QUELLE': 'Quelle: {quelle}, Stand {datum}', 'UI-ORT-DEIN-ORT': 'Ist das dein Ort? Hier bestätigen',
  'UI-ORT-BEANSPRUCHEN': 'Ich betreibe diesen Ort', 'UI-ORT-BEANSPRUCHEN-ERKL': 'Ein Mensch prüft das, in der Regel binnen 24 Stunden. Danach trägt der Eintrag das Kennzeichen „vom Ort bestätigt“.',
  'UI-ORT-ENTFERNEN': 'Bitte entfernen', 'UI-ORT-ENTFERNEN-ERKL': 'Der Eintrag wird entfernt und nicht wieder aufgenommen.', 'UI-ORT-ROLLE': 'Rolle (z. B. Inhaber)',
  'UI-ORT-EMAIL-ERKL': 'Am besten eine Adresse mit der Domain des Ortes. Wir schicken einen Bestätigungslink.', 'UI-ORT-NACHWEIS': 'Wie können wir das prüfen? (freiwillig)',
  'UI-ORT-ANFRAGE-GESENDET': 'Danke. Deine Anfrage hat die Nummer {nummer}. Bitte bestätige zuerst den Link in der Mail.',
  'UI-ORT-BESTAETIGT-MAIL': 'Adresse bestätigt. Die Anfrage {nummer} wird jetzt geprüft, in der Regel binnen {stunden} Stunden.',
  'UI-ORT-ART-BAR': 'Bar', 'UI-ORT-ART-CAFE': 'Café', 'UI-ORT-ART-CLUB': 'Club', 'UI-ORT-ART-BERATUNG': 'Beratung', 'UI-ORT-ART-SAUNA': 'Sauna', 'UI-ORT-ART-RESTAURANT': 'Restaurant', 'UI-ORT-ART-KULTUR': 'Kultur', 'UI-ORT-ART-SPORT': 'Sport',
  'UI-TAG-MO': 'Mo', 'UI-TAG-DI': 'Di', 'UI-TAG-MI': 'Mi', 'UI-TAG-DO': 'Do', 'UI-TAG-FR': 'Fr', 'UI-TAG-SA': 'Sa', 'UI-TAG-SO': 'So',
  'UI-EREIGNIS-ZUSAGEN': '{zahl} Zusagen', 'UI-EREIGNIS-ZUSAGEN-TITEL': 'Zusagen', 'UI-EREIGNIS-GRUPPE': 'Gruppe zum Treffen', 'UI-EREIGNIS-ZUR-GRUPPE': 'Zur Gruppe',
  'UI-EREIGNIS-GRUPPE-AB': 'Die Gruppe öffnet am {zeit}.', 'UI-EREIGNIS-ZURUECKNEHMEN': 'Zusage zurücknehmen', 'UI-GRUPPE-SCHLIESST': 'Die Gruppe verschwindet am {zeit}.',

  'UI-ICH-PROFIL': 'Mein Profil', 'UI-ICH-MERKLISTE': 'Merkliste', 'UI-ICH-ABO': 'Abo', 'UI-ICH-EINSTELLUNGEN': 'Einstellungen', 'UI-ICH-RECHTLICHES': 'Rechtliches',
  'UI-ICH-RUECKMELDUNG': 'Was sollen wir besser machen?', 'UI-ICH-ANTWORT-GEWUENSCHT': 'Ich möchte eine Antwort',
  'UI-ICH-ANTWORT-HINWEIS': 'Nur dann speichern wir, von welchem Konto die Rückmeldung kommt.', 'UI-ICH-DANKE': 'Danke!', 'UI-ICH-ABMELDEN': 'Abmelden',
  'UI-SIC-DIESES-GESPRAECH': 'Dieses Gespräch', 'UI-SIC-GESPRAECH-MELDEN': 'Dieses Gespräch melden', 'UI-SIC-GESPRAECH-BLOCKIEREN': 'Blockieren',
  'UI-SIC-STANDORT': 'Standort und Zonen', 'UI-SIC-WAS-WIR-PRUEFEN': 'Was wir prüfen — und was nicht',
  'UI-CHECKIN-LAEUFT': 'Dein Check-in läuft. Wir fragen:', 'UI-CHECKIN-BEENDEN': 'Check-in beenden', 'UI-CHECKIN-SPAETER': 'Beginnt später',
  'UI-CHECKIN-BEGINN': 'Beginn', 'UI-CHECKIN-NICHTS': 'Nichts tun', 'UI-CHECKIN-BENACHRICHTIGEN': 'Meine Vertrauenspersonen benachrichtigen',
  'UI-CHECKIN-KONTAKT': 'E-Mail-Adresse oder Telefonnummer', 'UI-CHECKIN-NACHRICHT': 'Nachricht an deine Vertrauenspersonen',
  'UI-CHECKIN-NACHRICHT-HINWEIS': 'Schreib, wo du bist und mit wem. Unser Name steht nicht darin.',
  'UI-CHECKIN-WEITERGEREICHT': 'Die Nachricht an deine Vertrauenspersonen ist unterwegs.', 'UI-CHECKIN-OPFERTELEFON': 'Hilfetelefon für Betroffene: {nummer}',
  'UI-TREFFPUNKT-VORSCHLAGEN': 'Im Chat vorschlagen',
  'UI-VERSTECKEN-WEB-GRENZE': 'Die Web-App kann ihr Symbol auf dem Home-Bildschirm nicht nachträglich ändern und kein Tippen auf die Geräterückseite erkennen. Was hier steht, ist alles, was sie kann.',
  'UI-VERSTECKEN-PIN-GESETZT': 'PIN gesetzt.', 'UI-VERSTECKEN-VORSCHAU': 'Das erscheint nach dem Verstecken:', 'UI-VERSTECKEN-JETZT': 'Jetzt verstecken',
  'UI-VERSTECKT-TITEL': 'Einkaufsliste', 'UI-VERSTECKT-1': 'Milch', 'UI-VERSTECKT-2': 'Brot', 'UI-VERSTECKT-3': 'Kaffee', 'UI-VERSTECKT-ENTSPERREN': 'Weitere Optionen',
  'UI-PIN-FALSCH': 'Das hat nicht geklappt.', 'UI-MITTEILUNG-UNGELESEN': 'ungelesen',
  'UI-DATEN-GESPEICHERT': 'Was gespeichert ist', 'UI-DATEN-KONTO': 'Konto', 'UI-DATEN-KONTO-ERKL': 'Angelegt am {datum}. Adresse oder Nummer nur verschlüsselt.',
  'UI-DATEN-PROFIL': 'Profil', 'UI-DATEN-PROFIL-ERKL': 'Name, Absicht, Angaben, {zahl} Fotos.', 'UI-DATEN-NACHRICHTEN': 'Nachrichten',
  'UI-DATEN-NACHRICHTEN-ERKL': '{gespraeche} Gespräche, {nachrichten} eigene Nachrichten — verschlüsselt.', 'UI-DATEN-STANDORT': 'Standortstufe',
  'UI-DATEN-STANDORT-ERKL': 'Stufe „{stufe}“. Gespeichert ist nur eine Rasterzelle, nie ein Verlauf.', 'UI-DATEN-MELDUNGEN': 'Meldungen',
  'UI-DATEN-MELDUNGEN-ERKL': '{zahl} Meldungen von dir.', 'UI-DATEN-ALBUM': 'Privates Album', 'UI-DATEN-ALBUM-ERKL': '{zahl} Bilder.',
  'UI-DATEN-EINWILLIGUNGEN': 'Einwilligungen', 'UI-DATEN-EINWILLIGUNG-ART9': 'Einwilligung nach Art. 9 DSGVO', 'UI-DATEN-EINWILLIGUNG': 'Einwilligung',
  'UI-DATEN-WIDERRUFEN': 'widerrufen am {datum}', 'UI-DATEN-WIDERRUFEN-KNOPF': 'Widerrufen',
  'UI-DATEN-WIDERRUF-FOLGE': 'Ohne diese Einwilligung lässt sich das Konto nicht fortführen. Es wird dann wie bei einer Löschung nach {tage} Tagen gelöscht.',
  'UI-DATEN-EXPORT-PASSWORT': 'Passwort für die Datei', 'UI-DATEN-EXPORT-PASSWORT-ERKL': 'Mindestens 8 Zeichen. Damit öffnest du die verschlüsselte ZIP-Datei.',
  'UI-DATEN-HERUNTERLADEN': 'Herunterladen',
  'UI-ABO-NOCH-NICHT': 'Das Abo startet später. Bis dahin ist alles kostenlos.', 'UI-ABO-KOSTENLOS-BLEIBT': 'Kostenlos bleibt',
  'UI-ABO-FREI-1': 'Blockieren und Melden', 'UI-ABO-FREI-2': 'Zonen mit Ersatzpunkt', 'UI-ABO-FREI-3': 'Check-in vor dem Treffen', 'UI-ABO-FREI-4': 'Schnell verstecken', 'UI-ABO-FREI-5': 'Deine Daten herunterladen und löschen',
  'UI-EINST-MITTEILUNGEN': 'Mitteilungen', 'UI-EINST-PUSH-NICHT-MOEGLICH': 'Dieser Browser kann keine Mitteilungen empfangen.', 'UI-EINST-RUHE-VON': 'Ruhezeit von', 'UI-EINST-RUHE-BIS': 'Ruhezeit bis', 'UI-EINST-KONTO': 'Konto',
  'UI-BLOCKIERT-LEER': 'Du hast niemanden blockiert.', 'UI-BLOCKIERT-BIS': 'rücknehmbar bis {datum}', 'UI-BLOCKIERT-ENDGUELTIG': 'endgültig',
  'UI-HILFE-MEINE': 'Deine Anfragen', 'UI-HILFE-ANTWORTEN': 'Antworten', 'UI-HILFE-STAND': 'Stand eines Vorgangs', 'UI-HILFE-FALLNUMMER': 'Fallnummer', 'UI-HILFE-NACHSEHEN': 'Nachsehen',
  'UI-HOME-SCHRITT-1': 'Tippe unten in Safari auf „Teilen“ (Quadrat mit Pfeil).', 'UI-HOME-SCHRITT-2': 'Wähle „Zum Home-Bildschirm“.', 'UI-HOME-SCHRITT-3': 'Tippe auf „Hinzufügen“ und öffne die App ab jetzt von dort.',

  'UI-OEFF-MELDEN-TITEL': 'Etwas melden (ohne Konto)', 'UI-OEFF-MELDEN-TEXT': 'Du brauchst kein Konto, um einen Inhalt zu melden. Ein Mensch prüft jede Meldung.',
  'UI-OEFF-MELDEN-WO': 'Wo ist der Inhalt?', 'UI-OEFF-MELDEN-WO-ERKL': 'Profilname, Stadt, Ort oder eine andere genaue Beschreibung.',
  'UI-OEFF-MELDEN-WARUM': 'Warum ist das rechtswidrig oder verstößt gegen die Regeln?', 'UI-OEFF-MELDEN-NAME': 'Dein Name',
  'UI-OEFF-MELDEN-CSAM-ANONYM': 'Bei Verdacht auf Missbrauchsdarstellungen darfst du Name und Adresse weglassen.',
  'UI-OEFF-MELDEN-GUTER-GLAUBE': 'Ich bin in gutem Glauben davon überzeugt, dass die Angaben richtig und vollständig sind.',
  'UI-OEFF-MELDEN-DANKE': 'Danke. Deine Meldung hat die Nummer {fallnummer}.', 'UI-OEFF-MODZEITEN-TITEL': 'Wie schnell wir prüfen',
  'UI-MODZEIT-KETTE': 'Automatische Prüfung eines Profilfotos: meist unter {sekunden} Sekunden.',
  'UI-MODZEIT-GRAU': 'Unklare Fotos prüft ein Mensch: tagsüber ({von}–{bis} Uhr) binnen {tag} Stunden, spätestens nach {gesamt} Stunden.',
  'UI-MODZEIT-MELDUNG': 'Meldungen entscheiden wir binnen {stunden} Stunden.', 'UI-MODZEIT-EINSPRUCH': 'Einspruch gegen ein abgelehntes Foto: Antwort binnen {stunden} Stunden.',
  'UI-MODZEIT-WIDERSPRUCH': 'Widerspruch gegen andere Entscheidungen: Antwort binnen {stunden} Stunden.',
  'UI-MODZEIT-HASH-AN': 'Der Abgleich mit bekannten Missbrauchsdarstellungen ist eingeschaltet.',
  'UI-MODZEIT-HASH-AUS': 'Der Abgleich mit bekannten Missbrauchsdarstellungen ist noch nicht eingeschaltet — deshalb läuft nur ein Testbetrieb mit erfundenen Daten.',
  'UI-RECHT-IMPRESSUM': 'Impressum', 'UI-RECHT-BEDINGUNGEN': 'Nutzungsbedingungen', 'UI-RECHT-DATENSCHUTZ': 'Datenschutzerklärung', 'UI-RECHT-KONTAKTSTELLEN': 'Kontaktstellen (Art. 11 und 12 DSA)',
  'UI-RECHT-ENTWURF': 'Entwurf — der verbindliche Text kommt vom Anwalt, bevor echte Menschen die App nutzen.',
  'UI-RECHT-IMPRESSUM-TEXT': '[Angaben nach § 5 DDG: Anbieter, Anschrift, Vertretung, Kontakt, Registereintrag — vor dem Start einzutragen]',
  'UI-RECHT-BEDINGUNGEN-TEXT': '[Nutzungsbedingungen — Entwurf in der Rechtsprüfung. Kurzfassung: die vier Sätze des Community-Vertrags.]',
  'UI-RECHT-DATENSCHUTZ-TEXT': '[Datenschutzerklärung — Entwurf in der Rechtsprüfung. Verantwortlicher, Zwecke, Rechtsgrundlagen (Art. 9 Abs. 2 lit. a DSGVO), Empfänger, Speicherfristen, Rechte.]',
  'UI-RECHT-KONTAKTSTELLEN-TEXT': 'Kontaktstelle für Behörden (Art. 11 DSA) und für Nutzerinnen und Nutzer (Art. 12 DSA): über „Hilfe und Kontakt“. Sprachen: Deutsch, Englisch. [Adresse vor dem Start einzutragen]',
  'UI-GAST-STADT-HINWEIS': '',
}
T.update(APP)

# Funktionen aus den Issues #11–#30 stehen in einer eigenen Datei
import sys
sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ui_funktionen import ERSETZT, NEU  # noqa: E402
from ui_v040 import ERSETZT as ERSETZT_040, NEU as NEU_040  # noqa: E402  (Issues #32–#39)
for _neu, _ersetzt in ((NEU, ERSETZT), (NEU_040, ERSETZT_040)):
    for _k in _neu:
        if _k in T:
            raise SystemExit(f'Text {_k} doppelt')
    T.update(_neu)
    for _k in _ersetzt:
        if _k not in T:
            raise SystemExit(f'Text {_k} gibt es nicht — in NEU eintragen')
    T.update(_ersetzt)

FAQ = [
  ('Ich komme nicht mehr in mein Konto — was kann ich tun?', 'Auf der Anmeldeseite unter „Passwort vergessen“ schicken wir dir einen Code an deine bestätigte Adresse oder Nummer. Hast du beides nicht mehr, hilft dein Wiederherstellungscode oder der Weg über eine Vertrauensperson.'),
  ('Ich habe meinen Wiederherstellungscode verloren.', 'Solange du angemeldet bist, kannst du unter „Ich“ → „Konto“ einen neuen Code erzeugen. Der alte gilt dann nicht mehr.'),
  ('Warum muss ich mein Alter prüfen lassen, bevor ich schreiben kann?', 'Weil hier nur Volljährige sein dürfen. Wir speichern davon nur „geprüft ja/nein“, den Zeitpunkt und den Weg — kein Geburtsdatum. Ein Foto deines Ausweises behalten wir nur, solange ein Mensch aus unserem Team es prüfen muss; danach löschen wir es.'),
  ('Was passiert mit meinem Selfie bei der Altersprüfung?', 'Die Prüfung macht ein Prüfpartner. Wir erhalten nur das Ergebnis. Was der Partner speichert und wie lange, steht in unserer Datenschutzerklärung.'),
  ('Warum sehe ich manche Profile nicht?', 'Wer dich blockiert hat oder wen du blockiert hast, erscheint nicht. Manche Personen sind nur für bestimmte Gruppen sichtbar oder gerade unsichtbar.'),
  ('Wie genau wird mein Standort angezeigt?', 'Nie genau. Wir runden auf ein Raster (ungefähr 2 km oder 500 m, je nach Einstellung) und zeigen anderen nur eine Entfernungsstufe, keine Meter.'),
  ('Was ist eine Zone, und wie viele sind kostenlos?', 'Eine Zone ist ein Bereich, etwa um deine Wohnung. Darin zeigen wir statt deines Ortes einen Ersatzpunkt. Die Zahl der Zonen steht in den Einstellungen.'),
  ('Wie verstecke ich die App auf meinem Gerät?', 'Mit dem schnellen Ausblenden: dreimal schnell auf den Titel oben tippen oder zweimal Escape drücken. Die App wechselt sofort auf eine neutrale Seite. Zurück geht es genauso: dreimal schnell oben auf den Bildschirm tippen (oder zweimal Escape) und die PIN eingeben.'),
  ('Wie blockiere ich jemanden, und was sieht die Person davon?', 'Im Profil oder Gespräch unter „Blockieren“. Die Person erhält keine Nachricht — sie sieht dich nur nicht mehr. Eine Weile lang kannst du es zurücknehmen.'),
  ('Ich habe jemanden gemeldet — wie geht es weiter?', 'Ein Mensch prüft die Meldung, in der Regel innerhalb von 24 Stunden. Das Ergebnis steht in deinen Mitteilungen. Wer gemeldet hat, sagen wir niemandem.'),
  ('Wie lange bleiben meine Nachrichten gespeichert?', 'Solange das Gespräch besteht. Beendete Gespräche liegen 24 Stunden im Archiv und sind danach bei beiden gelöscht. Verschwindende Nachrichten gehen schon früher.'),
  ('Wie lösche ich mein Konto, und was passiert dann mit meinen Daten?', 'Unter „Ich“ → „Meine Daten“. Du hast danach 30 Tage Zeit, es dir anders zu überlegen. Dann löschen wir alles, bis auf das, was wir gesetzlich aufbewahren müssen.'),
  ('Wie bekomme ich eine Kopie meiner Daten?', 'Unter „Ich“ → „Meine Daten“ → „Kopie anfordern“. Du bekommst eine verschlüsselte ZIP-Datei mit einem Passwort, das nur du kennst.'),
  ('Meine Zahlung ist nicht angekommen.', 'Schreib uns mit der Kategorie „Zahlung und Abo“ — mit dem ungefähren Zeitpunkt. Zahlungsdaten brauchen wir nicht.'),
  ('Wie kündige ich mein Abo?', 'Dort, wo du es abgeschlossen hast. Im Web unter „Ich“ → „Abo“, mit zwei Klicks.'),
  ('Was genau ist im Abo enthalten — und was bleibt kostenlos?', 'Alles, was mit Sicherheit zu tun hat, bleibt kostenlos: Blockieren, Melden, Zonen, Check-in, Ausblenden. Das Abo bringt Komfort, keine Sicherheit.'),
  ('Warum wurde mein Foto abgelehnt?', 'Der Grund steht in deinen Mitteilungen, oft mit der markierten Stelle. Du kannst innerhalb von 48 Stunden Einspruch einlegen — ein Mensch prüft das.'),
  ('Mein Konto wurde eingeschränkt — warum, und was kann ich tun?', 'Der Grund steht in deinen Mitteilungen. Dort kannst du widersprechen. Es entscheidet dann jemand anderes als die Person, die eingeschränkt hat.'),
  ('Wie melde ich einen Ort oder eine Veranstaltung?', 'Über „Schreib uns“ mit der Kategorie „Ein Ort oder eine Veranstaltung“.'),
  ('Wie erreiche ich einen Menschen?', 'Über „Schreib uns“ unten auf dieser Seite. Ein Mensch liest jede Nachricht.'),
]
for i, (q, a) in enumerate(FAQ, 1):
    T[f'UI-FAQ-{i:02d}-F'] = q
    T[f'UI-FAQ-{i:02d}-A'] = a

out = {k: {'t': v, 's': 'ENTWURF'} for k, v in T.items()}
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, 'ui-de.json'), 'w', encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False, indent=1, sort_keys=True)
    f.write('\n')
print(len(out), 'Texte geschrieben')
