"""Oberflächentexte der Funktionen aus den Issues #11–#30 (Herbst 2026). Alle ENTWURF.
Wird von build-ui.py eingelesen — nicht allein aufrufen."""

NEU = {
  # ───── #12 Entfernungen ─────
  'UI-KM-UNTER-1': '< 1 km',
  'UI-KM': '{km} km',

  # ───── #13 Profil ─────
  'UI-PROFIL-UEBER-MICH': 'Über mich',
  'UI-PROFIL-GROESSE': 'Größe (cm)',
  'UI-PROFIL-GEWICHT': 'Gewicht (kg)',
  'UI-PROFIL-POSITION': 'Position',
  'UI-PROFIL-KOERPERTYP': 'Körpertyp',
  'UI-KOERPERTYP-MAX': 'Höchstens {max} Körpertypen.',
  'UI-PROFIL-KINKS': 'Kinks und Fetische',
  'UI-PROFIL-KINKS-ERKL': 'Ganz freiwillig. Was du auswählst, steht sichtbar in deinem Profil. Du kannst es jederzeit wieder entfernen.',
  'UI-KINKS-MAX': 'Höchstens {max} Angaben.',
  'UI-PROFIL-FREITEXT-ZAEHLER': '{zahl}/{max}',
  'UI-PROFIL-KEINE-ANGABE': 'Keine Angabe',
  'UI-PROFIL-TIPPEN-BEARBEITEN': 'Tippen zum Bearbeiten',
  'UI-FOTOS-ANZAHL': '{zahl} von {max} Fotos',
  'UI-PROFIL-VORSCHAU': 'So sehen dich andere',
  'UI-TAB-ICH-PROFIL': 'Ich',
  'UI-FOTO-IN-PRUEFUNG': 'in Prüfung',
  'UI-FOTO-ALS-ERSTES': 'Als erstes Foto zeigen',
  'UI-APP-NEUES': 'Neues',

  # ───── #22 Raster ─────
  'UI-RASTER-TRENNER': 'Das war’s in {x} km. Etwas weiter weg (bis {y} km):',
  'UI-RASTER-NEU-REIHE': 'Neu in deiner Nähe',
  'UI-RASTER-NEU': 'Neu',
  'UI-RASTER-RADIUS': 'Umkreis',
  'UI-RASTER-RADIUS-WERT': '{km} km',
  'UI-RASTER-RADIUS-ERKL': 'Alle, die in diesem Umkreis sichtbar sind, siehst du immer — nur die Reihenfolge wird gemischt.',
  'UI-RASTER-ERWEITERN': 'Auch Profile außerhalb meines Radius anzeigen',
  'UI-RASTER-ERWEITERN-ERKL': 'Sind es weniger als {zahl}, zeigen wir darunter Profile weiter weg — getrennt, bis höchstens {km} km.',
  'UI-RASTER-ENDE': 'Das sind alle.',
  'UI-RASTER-LEER': 'Im Umkreis von {km} km ist gerade niemand zu sehen.',
  'UI-RASTER-LEER-ERWEITERN': 'Umkreis vergrößern',
  'UI-RASTER-LAEDT': 'Lädt weitere Profile …',
  'UI-RASTER-UMKREIS-TITEL': 'Umkreis',
  'UI-RASTER-ANWENDEN': 'Übernehmen',
  'UI-RASTER-TRAVEL': 'Du stöberst in {ort}.',

  # ───── #20 Suche und Filter ─────
  'UI-SUCHE': 'Suchen',
  'UI-SUCHE-TITEL': 'Namen suchen',
  'UI-SUCHE-PLATZHALTER': 'Name',
  'UI-SUCHE-ZU-KURZ': 'Mindestens {zahl} Zeichen.',
  'UI-SUCHE-KEINE': 'Niemand mit diesem Namen im Umkreis von {km} km.',
  'UI-SUCHE-ERKL': 'Gesucht wird im Umkreis von {km} km — nur Profile, die gefunden werden möchten. Die Filter gelten auch hier.',
  'UI-SUCHE-TREFFER': '{zahl} Treffer',
  'UI-EINST-AUFFINDBAR': 'Über die Namenssuche auffindbar',
  'UI-EINST-AUFFINDBAR-ERKL': 'Aus: Andere finden dich nicht über deinen Namen. Im Raster bleibst du sichtbar.',
  'UI-FILTER-GEWICHT': 'Gewicht (kg)',
  'UI-FILTER-GROESSE': 'Größe (cm)',
  'UI-FILTER-KOERPERTYP': 'Körpertyp',
  'UI-FILTER-KINKS': 'Kinks und Fetische',
  'UI-FILTER-POSITION': 'Position',
  'UI-FILTER-ANTWORTET': 'Antwortet meistens oder besser',
  'UI-FILTER-MIT-FOTO': 'Nur mit Foto',
  'UI-FILTER-AKTIV': '{zahl} aktiv',
  'UI-FILTER-BEREICH-AN': 'Bereich festlegen',
  'UI-FILTER-ODER': 'Mindestens eins davon',

  # ───── #14 Ungelesen ─────
  'UI-CHATS-UNGELESEN': '{zahl} ungelesen',
  'UI-CHAT-NEUE-NACHRICHTEN': 'Neue Nachrichten',

  # ───── #21 Vorlagen und Emojis ─────
  'UI-VORLAGEN': 'Vorlagen',
  'UI-VORLAGEN-TITEL': 'Vorformulierte Nachrichten',
  'UI-VORLAGEN-ERKL': 'Ein Tipp sendet den Text so, wie er hier steht.',
  'UI-VORLAGEN-LEER': 'Noch keine Vorlagen. Leg dir Antworten auf Fragen an, die immer wieder kommen.',
  'UI-VORLAGEN-NEU': 'Neue Vorlage',
  'UI-VORLAGEN-BEARBEITEN': 'Bearbeiten',
  'UI-VORLAGEN-FERTIG': 'Fertig',
  'UI-VORLAGEN-MAX': 'Höchstens {max} Vorlagen.',
  'UI-VORLAGEN-PLATZHALTER': 'z. B. „Ich bin eher spontan unterwegs – schreib mir einfach, wenn du in der Nähe bist.“',
  'UI-EMOJI': 'Emoji',
  'UI-EMOJI-GRUPPE-1': 'Smileys',
  'UI-EMOJI-GRUPPE-2': 'Gesten',
  'UI-EMOJI-GRUPPE-3': 'Herzen',
  'UI-EMOJI-GRUPPE-4': 'Unterwegs',
  'UI-EMOJI-GRUPPE-5': 'Essen und Trinken',
  'UI-EMOJI-GRUPPE-6': 'Symbole',

  # ───── #23 Alben ─────
  'UI-ALBEN': 'Private Alben',
  'UI-ALBEN-ERKL': 'Bis zu {max} Alben mit je {bilder} Bildern. Du teilst sie im Chat mit einem Tipp — sehen kann sie nur, wem du sie zeigst.',
  'UI-ALBEN-MAX': 'Höchstens {max} Alben.',
  'UI-ALBEN-NEU': 'Neues Album',
  'UI-ALBEN-NAME': 'Name des Albums',
  'UI-ALBEN-UMBENENNEN': 'Umbenennen',
  'UI-ALBEN-LOESCHEN': 'Album löschen',
  'UI-ALBEN-LOESCHEN-FRAGE': 'Album mit allen Bildern löschen? Wer es gerade sehen darf, sieht es danach nicht mehr.',
  'UI-ALBEN-BILDER': '{zahl} Bilder',
  'UI-ALBEN-WAEHLEN': 'Welches Album teilen?',
  'UI-ALBEN-LEER-TEILEN': 'Leg zuerst ein Album mit Bildern an.',
  'UI-ALBEN-GETEILT': 'Album geteilt.',
  'UI-ALBUM-GETEILT-VON': '{name} teilt ein Album mit dir: „{album}“',

  # ───── #26 Einmal-Bilder ─────
  'UI-EINMAL': 'Einmal ansehen',
  'UI-EINMAL-HINWEIS': 'Das Bild verschwindet nach dem Ansehen. Screenshots oder Fotos vom Bildschirm können wir aber nicht verhindern. Schick nur, was du wirklich teilen willst.',
  'UI-EINMAL-VERSTANDEN': 'Verstanden',
  'UI-EINMAL-KACHEL': 'Einmal-Bild · Tippen zum Ansehen',
  'UI-EINMAL-ANGESEHEN': 'Angesehen',
  'UI-EINMAL-ABGELAUFEN': 'Abgelaufen',
  'UI-EINMAL-GESENDET': 'Einmal-Bild · Gesendet',
  'UI-EINMAL-ANZEIGE': 'Verschwindet nach dem Ansehen, kann aber abfotografiert werden.',
  'UI-EINMAL-NOCH': 'noch {sekunden} s',
  'UI-EINMAL-WEG': 'Dieses Bild ist nicht mehr verfügbar.',
  'UI-EINMAL-SENDEN': 'Als Einmal-Bild senden',

  # ───── #28 Sprachnachrichten ─────
  'UI-SPRACHE': 'Sprachnachricht',
  'UI-SPRACHE-HALTEN': 'Zum Aufnehmen gedrückt halten — oder tippen zum Starten',
  'UI-SPRACHE-NIMMT-AUF': 'Aufnahme läuft · {zeit}',
  'UI-SPRACHE-WISCHEN': '‹ Zum Abbrechen wischen',
  'UI-SPRACHE-STOPP': 'Stopp',
  'UI-SPRACHE-ABBRECHEN': 'Abbrechen',
  'UI-SPRACHE-SENDEN': 'Senden',
  'UI-SPRACHE-LOESCHEN': 'Löschen',
  'UI-SPRACHE-ANHOEREN': 'Anhören',
  'UI-SPRACHE-ERST-ANTWORT': 'Sprachnachrichten gehen, sobald er geantwortet hat.',
  'UI-SPRACHE-AUS': 'Diese Person empfängt gerade keine Sprachnachrichten.',
  'UI-SPRACHE-ZU-LANG': 'Höchstens {sekunden} Sekunden.',
  'UI-SPRACHE-ZU-GROSS': 'Die Aufnahme ist zu groß (höchstens {mb} MB).',
  'UI-SPRACHE-LEER': 'Die Aufnahme ist leer.',
  'UI-SPRACHE-FORMAT': 'Diese Aufnahme können wir nicht verarbeiten.',
  'UI-SPRACHE-NICHT-MOEGLICH': 'Sprachnachrichten sind gerade nicht möglich.',
  'UI-SPRACHE-MIKRO-ABGELEHNT': 'Das Mikrofon ist gesperrt. Erlaube es in den Einstellungen deines Browsers für diese Seite.',
  'UI-SPRACHE-MIKRO-FEHLT': 'Kein Mikrofon gefunden.',
  'UI-SPRACHE-HTTPS': 'Aufnahmen gehen nur über eine sichere Verbindung (https).',
  'UI-SPRACHE-BROWSER': 'Dieser Browser kann keine Aufnahmen machen.',
  'UI-SPRACHE-TEMPO': 'Tempo {tempo}',
  'UI-EINST-SPRACHE': 'Sprachnachrichten empfangen',
  'UI-EINST-SPRACHE-ERKL': 'Aus: Niemand kann dir Sprachnachrichten schicken. Das gilt auch in Cruizy Date.',

  # ───── #30 Gesprächsstarter ─────
  'UI-STARTER-TITEL': 'Ideen für den Anfang',
  'UI-STARTER-ANDERE': 'Andere Vorschläge',
  'UI-EINST-STARTER': 'Gesprächsstarter anzeigen',
  'UI-EINST-STARTER-ERKL': 'In neuen Chats schlagen wir dir ein paar Einstiege vor — aus dem, was im Profil der anderen Person steht. Nichts davon verlässt unseren Server.',

  # ───── #24 Antwortquote ─────
  'UI-AQ-INFO-TITEL': 'Was bedeutet das?',
  'UI-AQ-INFO-1': 'Das zeigt, wie zuverlässig jemand auf erste Nachrichten reagiert.',
  'UI-AQ-INFO-2-TITEL': 'So wird’s berechnet:',
  'UI-AQ-INFO-2': 'Wir schauen auf die letzten {tage} Tage. Als Antwort zählt jede Reaktion innerhalb von 3 Tagen, auch eine freundliche Absage.',
  'UI-AQ-INFO-3-TITEL': 'Kein Abzeichen?',
  'UI-AQ-INFO-3': 'Das heißt nicht, dass jemand nicht antwortet. Vielleicht ist er neu oder bekommt gerade wenige Nachrichten.',
  'UI-AQ-EIGEN': 'Deine Antwortquote: {prozent} % · {stufe}',
  'UI-AQ-EIGEN-OHNE-STUFE': 'Deine Antwortquote: {prozent} %',
  'UI-AQ-EIGEN-ERKL': 'Die Quote zählt, wie oft du in den letzten {tage} Tagen innerhalb von 3 Tagen auf neue Nachrichten reagiert hast.',
  'UI-AQ-TIPP': 'Tipp: Kein Interesse? Mit „Absagen“ antwortest du mit einem Tipp freundlich, und das zählt als Antwort.',
  'UI-AQ-NOCH-KEINE': 'Deine Antwortquote: Sobald du genug Nachrichten bekommen hast, siehst du hier deine Quote.',
  'UI-AQ-FORTSCHRITT': '{zahl} von {min} Unterhaltungen gezählt',

  # ───── #29 Vollständigkeit ─────
  'UI-VOLL-TITEL': 'Dein Profil ist zu {prozent} % fertig',
  'UI-VOLL-FERTIG': 'Dein Profil ist komplett!',
  'UI-VOLL-HINWEIS': 'Dein Profil ist erst zu {prozent} % fertig. Mit ein paar Angaben mehr bekommst du deutlich mehr Nachrichten.',
  'UI-VOLL-JETZT': 'Jetzt ergänzen',
  'UI-VOLL-TIPP-PROFILBILD': 'Lade ein Profilbild hoch – Profile mit Bild bekommen deutlich mehr Nachrichten.',
  'UI-VOLL-TIPP-DREI-FOTOS': 'Füg noch {zahl} Fotos hinzu.',
  'UI-VOLL-TIPP-DREI-FOTOS-1': 'Füg noch ein Foto hinzu.',
  'UI-VOLL-TIPP-BIO': 'Schreib ein paar Sätze über dich.',
  'UI-VOLL-TIPP-BASIS': 'Ergänze Alter, Größe, Gewicht und Körpertyp.',
  'UI-VOLL-TIPP-FOTO-ECHT': 'Lass dein Foto verifizieren – das schafft Vertrauen.',
  'UI-VOLL-TIPP-INTERESSEN': 'Wähle ein paar Interessen aus.',
  'UI-VOLL-TIPP-ABSICHT': 'Setz eine Absicht – dann wissen andere, was du gerade suchst.',

  # ───── #27 Profilbesucher ─────
  'UI-BESUCHER': 'Profilbesucher',
  'UI-BESUCHER-ANZAHL': '{zahl} Besucher in den letzten {tage} Tagen',
  'UI-BESUCHER-NEU': '{zahl} neu',
  'UI-BESUCHER-KEINE': 'In den letzten {tage} Tagen hat niemand dein Profil geöffnet.',
  'UI-BESUCHER-PREMIUM': 'Wer dein Profil angesehen hat, siehst du mit PLUS.',
  'UI-BESUCHER-PREMIUM-KNOPF': 'PLUS ansehen',
  'UI-BESUCHER-HEUTE': 'heute',
  'UI-BESUCHER-GESTERN': 'gestern',
  'UI-BESUCHER-WOCHE': 'diese Woche',
  'UI-BESUCHER-FRUEHER': 'früher',
  'UI-BESUCHER-UNSICHTBAR': 'Unsichtbar stöbern',
  'UI-BESUCHER-UNSICHTBAR-ERKL': 'Deine Besuche werden nicht gespeichert. Andere sehen nicht, dass du ihr Profil angesehen hast.',
  'UI-BESUCHER-UNSICHTBAR-PLUS': 'Nur mit PLUS.',
  'UI-ABO-TEST': 'PLUS im Testbetrieb 7 Tage ausprobieren',
  'UI-ABO-TEST-AKTIV': 'PLUS ist aktiv bis {datum}.',
  'UI-ABO-TEST-BEENDEN': 'PLUS beenden',

  # ───── #25 Gesundheit und Tests ─────
  'UI-TEST-BEREICH': 'Gesundheit & Tests',
  'UI-TEST-SCHALTER': 'Erinnere mich an einen Test',
  'UI-TEST-SCHALTER-ERKL': 'Auf sexuell übertragbare Infektionen. Freiwillig, nur für dich sichtbar, nie im Profil.',
  'UI-TEST-INTERVALL': 'Wie oft?',
  'UI-TEST-MONATE-1': 'jeden Monat',
  'UI-TEST-MONATE-3': 'alle 3 Monate',
  'UI-TEST-MONATE-6': 'alle 6 Monate',
  'UI-TEST-EINWILLIGUNG': 'Ich willige ein, dass Cruizy mein Erinnerungsintervall und das Datum der nächsten Erinnerung speichert, um mich zu erinnern. Diese Angaben sind nur für mich sichtbar, werden nicht im Profil angezeigt und nie weitergegeben. Ich kann das jederzeit ausschalten, dann werden die Daten gelöscht.',
  'UI-TEST-AKTIVIEREN': 'Erinnerung einschalten',
  'UI-TEST-NAECHSTE': 'Nächste Erinnerung: {datum}',
  'UI-TEST-GERADE': 'Ich war gerade testen',
  'UI-TEST-KANAL-PUSH': 'Per Push-Mitteilung',
  'UI-TEST-KANAL-APP': 'Als Hinweis in der App',
  'UI-TEST-KANAL': 'Wähle mindestens einen Weg.',
  'UI-TEST-PUSH': 'Du hast eine Erinnerung.',
  'UI-TEST-TITEL': 'Zeit für deinen Check!',
  'UI-TEST-TEXT': 'Regelmäßig testen schützt dich und andere.',
  'UI-TEST-TESTSTELLEN': 'Teststellen finden',
  'UI-TEST-ERLEDIGT': 'Erledigt',
  'UI-TEST-WOCHE': 'In einer Woche erinnern',
  'UI-TEST-AUS': 'Erinnerung ausschalten',
  'UI-TEST-AUS-FERTIG': 'Ausgeschaltet. Deine Angaben sind gelöscht.',
  'UI-TEST-DATEN': 'Gespeichert sind nur: Intervall, Datum der nächsten Erinnerung, Zeitpunkt deiner Einwilligung.',

  # ───── #18 Travel (Grundlage für das Raster) ─────
  'UI-TRAVEL-BEENDEN': 'Zurück zu meinem Ort',
  'UI-TRAVEL-BALD-REIHE': 'Bald in der Gegend',
  'UI-TRAVEL-BALD-KURZ': 'Bald in {ort}',
}

# Bestehende Texte, die sich durch die Issues ändern
ERSETZT = {
  'UI-FOTOS-MAX': 'Mehr als {max} Fotos gehen nicht.',
  'UI-ALBUM-MEINS': 'Private Alben',
}
