"""Oberflächentexte der Funktionen aus den Issues #11–#30 (Herbst 2026). Alle ENTWURF.
Wird von build-ui.py eingelesen — nicht allein aufrufen."""

NEU = {
  # ───── #11 Verstecken ─────
  'UI-TARN-TITEL': 'Tarnung',
  'UI-TARN-ERKL': 'Symbol und Name auf dem Home-Bildschirm — und die App, die nach dem Verstecken erscheint. Beides passt zusammen, damit nichts auffällt.',
  'UI-TARN-ZURUECK': 'Zurück in die App:',
  'UI-TARN-GESTE-A': 'Überschrift „Notizen“ lange drücken und die PIN eingeben.',
  'UI-TARN-GESTE-B': 'Die PIN in den Rechner tippen und „=“ drücken.',
  'UI-TARN-GESTE-C': 'Die große Temperatur lange drücken und die PIN eingeben.',
  'UI-TARN-GESTE-D': 'Den Monatsnamen lange drücken und die PIN eingeben.',
  'UI-APPSPERRE': 'App mit PIN sperren',
  'UI-APPSPERRE-ERKL': 'Beim Öffnen erscheint zuerst die Tarnung. Erst mit der PIN geht es weiter.',
  'UI-APPSPERRE-PIN-ZUERST': 'Leg zuerst eine PIN fest.',
  'UI-APPSPERRE-NACH': 'Wieder sperren, wenn die App so lange im Hintergrund war:',
  'UI-APPSPERRE-SOFORT': 'sofort',
  'UI-APPSPERRE-MIN': 'nach {min} Min.',

  # ───── #12 Entfernungen ─────
  'UI-KM-UNTER-1': '< 1 km',
  'UI-KM': '{km} km',

  # ───── #13 Profil ─────
  'UI-PROFIL-UEBER-MICH': 'Über mich',
  'UI-PROFIL-GROESSE': 'Größe (cm)',
  'UI-PROFIL-GEWICHT': 'Gewicht (kg)',
  'UI-PROFIL-POSITION': 'Position',
  'UI-PROFIL-KOERPERTYP': 'Körpertyp',
  'UI-KOERPERTYP-MAX': 'Höchstens {max} Körpertypen.',
  'UI-PROFIL-KINKS': 'Kinks und Fetische',
  'UI-PROFIL-KINKS-ERKL': 'Ganz freiwillig. Was du auswählst, steht sichtbar in deinem Profil. Du kannst es jederzeit wieder entfernen.',
  'UI-KINKS-MAX': 'Höchstens {max} Angaben.',
  'UI-PROFIL-FREITEXT-ZAEHLER': '{zahl}/{max}',
  'UI-PROFIL-KEINE-ANGABE': 'Keine Angabe',
  'UI-PROFIL-TIPPEN-BEARBEITEN': 'Tippen zum Bearbeiten',
  'UI-FOTOS-ANZAHL': '{zahl} von {max} Fotos',
  'UI-PROFIL-VORSCHAU': 'So sehen dich andere',
  'UI-TAB-ICH-PROFIL': 'Ich',
  'UI-FOTO-IN-PRUEFUNG': 'in Prüfung',
  'UI-FOTO-ALS-ERSTES': 'Als erstes Foto zeigen',
  'UI-APP-NEUES': 'Neues',

  # ───── #22 Raster ─────
  'UI-RASTER-TRENNER': 'Das war’s in {x} km. Etwas weiter weg (bis {y} km):',
  'UI-RASTER-NEU-REIHE': 'Neu in deiner Nähe',
  'UI-RASTER-NEU': 'Neu',
  'UI-RASTER-RADIUS': 'Umkreis',
  'UI-RASTER-RADIUS-WERT': '{km} km',
  'UI-RASTER-RADIUS-ERKL': 'Alle, die in diesem Umkreis sichtbar sind, siehst du immer — nur die Reihenfolge wird gemischt.',
  'UI-RASTER-ERWEITERN': 'Auch Profile außerhalb meines Radius anzeigen',
  'UI-RASTER-ERWEITERN-ERKL': 'Sind es weniger als {zahl}, zeigen wir darunter Profile weiter weg — getrennt, bis höchstens {km} km.',
  'UI-RASTER-ENDE': 'Das sind alle.',
  'UI-RASTER-LEER': 'Im Umkreis von {km} km ist gerade niemand zu sehen.',
  'UI-RASTER-LEER-ERWEITERN': 'Umkreis vergrößern',
  'UI-RASTER-LAEDT': 'Lädt weitere Profile …',
  'UI-RASTER-UMKREIS-TITEL': 'Umkreis',
  'UI-RASTER-ANWENDEN': 'Übernehmen',
  'UI-RASTER-TRAVEL': 'Du stöberst in {ort}.',

  # ───── #20 Suche und Filter ─────
  'UI-SUCHE': 'Suchen',
  'UI-SUCHE-TITEL': 'Namen suchen',
  'UI-SUCHE-PLATZHALTER': 'Name',
  'UI-SUCHE-ZU-KURZ': 'Mindestens {zahl} Zeichen.',
  'UI-SUCHE-KEINE': 'Niemand mit diesem Namen im Umkreis von {km} km.',
  'UI-SUCHE-ERKL': 'Gesucht wird im Umkreis von {km} km — nur Profile, die gefunden werden möchten. Die Filter gelten auch hier.',
  'UI-SUCHE-TREFFER': '{zahl} Treffer',
  'UI-EINST-AUFFINDBAR': 'Über die Namenssuche auffindbar',
  'UI-EINST-AUFFINDBAR-ERKL': 'Aus: Andere finden dich nicht über deinen Namen. Im Raster bleibst du sichtbar.',
  'UI-FILTER-GEWICHT': 'Gewicht (kg)',
  'UI-FILTER-GROESSE': 'Größe (cm)',
  'UI-FILTER-KOERPERTYP': 'Körpertyp',
  'UI-FILTER-KINKS': 'Kinks und Fetische',
  'UI-FILTER-POSITION': 'Position',
  'UI-FILTER-ANTWORTET': 'Antwortet meistens oder besser',
  'UI-FILTER-MIT-FOTO': 'Nur mit Foto',
  'UI-FILTER-AKTIV': '{zahl} aktiv',
  'UI-FILTER-BEREICH-AN': 'Bereich festlegen',
  'UI-FILTER-ODER': 'Mindestens eins davon',

  # ───── #14 Ungelesen ─────
  'UI-CHATS-UNGELESEN': '{zahl} ungelesen',
  'UI-CHAT-NEUE-NACHRICHTEN': 'Neue Nachrichten',

  # ───── #21 Vorlagen und Emojis ─────
  'UI-VORLAGEN': 'Vorlagen',
  'UI-VORLAGEN-TITEL': 'Vorformulierte Nachrichten',
  'UI-VORLAGEN-ERKL': 'Ein Tipp sendet den Text so, wie er hier steht.',
  'UI-VORLAGEN-LEER': 'Noch keine Vorlagen. Leg dir Antworten auf Fragen an, die immer wieder kommen.',
  'UI-VORLAGEN-NEU': 'Neue Vorlage',
  'UI-VORLAGEN-BEARBEITEN': 'Bearbeiten',
  'UI-VORLAGEN-FERTIG': 'Fertig',
  'UI-VORLAGEN-MAX': 'Höchstens {max} Vorlagen.',
  'UI-VORLAGEN-PLATZHALTER': 'z. B. „Ich bin eher spontan unterwegs – schreib mir einfach, wenn du in der Nähe bist.“',
  'UI-EMOJI': 'Emoji',
  'UI-EMOJI-GRUPPE-1': 'Smileys',
  'UI-EMOJI-GRUPPE-2': 'Gesten',
  'UI-EMOJI-GRUPPE-3': 'Herzen',
  'UI-EMOJI-GRUPPE-4': 'Unterwegs',
  'UI-EMOJI-GRUPPE-5': 'Essen und Trinken',
  'UI-EMOJI-GRUPPE-6': 'Symbole',

  # ───── #23 Alben ─────
  'UI-ALBEN': 'Private Alben',
  'UI-ALBEN-ERKL': 'Bis zu {max} Alben mit je {bilder} Bildern. Du teilst sie im Chat mit einem Tipp — sehen kann sie nur, wem du sie zeigst.',
  'UI-ALBEN-MAX': 'Höchstens {max} Alben.',
  'UI-ALBEN-NEU': 'Neues Album',
  'UI-ALBEN-NAME': 'Name des Albums',
  'UI-ALBEN-UMBENENNEN': 'Umbenennen',
  'UI-ALBEN-LOESCHEN': 'Album löschen',
  'UI-ALBEN-LOESCHEN-FRAGE': 'Album mit allen Bildern löschen? Wer es gerade sehen darf, sieht es danach nicht mehr.',
  'UI-ALBEN-BILDER': '{zahl} Bilder',
  'UI-ALBEN-WAEHLEN': 'Welches Album teilen?',
  'UI-ALBEN-LEER-TEILEN': 'Leg zuerst ein Album mit Bildern an.',
  'UI-ALBEN-GETEILT': 'Album geteilt.',
  'UI-ALBUM-GETEILT-VON': '{name} teilt ein Album mit dir: „{album}“',

  # ───── #26 Einmal-Bilder ─────
  'UI-EINMAL': 'Einmal ansehen',
  'UI-EINMAL-HINWEIS': 'Das Bild verschwindet nach dem Ansehen. Screenshots oder Fotos vom Bildschirm können wir aber nicht verhindern. Schick nur, was du wirklich teilen willst.',
  'UI-EINMAL-VERSTANDEN': 'Verstanden',
  'UI-EINMAL-KACHEL': 'Einmal-Bild · Tippen zum Ansehen',
  'UI-EINMAL-ANGESEHEN': 'Angesehen',
  'UI-EINMAL-ABGELAUFEN': 'Abgelaufen',
  'UI-EINMAL-GESENDET': 'Einmal-Bild · Gesendet',
  'UI-EINMAL-ANZEIGE': 'Verschwindet nach dem Ansehen, kann aber abfotografiert werden.',
  'UI-EINMAL-NOCH': 'noch {sekunden} s',
  'UI-EINMAL-WEG': 'Dieses Bild ist nicht mehr verfügbar.',
  'UI-EINMAL-SENDEN': 'Als Einmal-Bild senden',

  # ───── #28 Sprachnachrichten ─────
  'UI-SPRACHE': 'Sprachnachricht',
  'UI-SPRACHE-HALTEN': 'Zum Aufnehmen gedrückt halten — oder tippen zum Starten',
  'UI-SPRACHE-NIMMT-AUF': 'Aufnahme läuft · {zeit}',
  'UI-SPRACHE-WISCHEN': '‹ Zum Abbrechen wischen',
  'UI-SPRACHE-STOPP': 'Stopp',
  'UI-SPRACHE-ABBRECHEN': 'Abbrechen',
  'UI-SPRACHE-SENDEN': 'Senden',
  'UI-SPRACHE-LOESCHEN': 'Löschen',
  'UI-SPRACHE-ANHOEREN': 'Anhören',
  'UI-SPRACHE-ERST-ANTWORT': 'Sprachnachrichten gehen, sobald er geantwortet hat.',
  'UI-SPRACHE-AUS': 'Diese Person empfängt gerade keine Sprachnachrichten.',
  'UI-SPRACHE-ZU-LANG': 'Höchstens {sekunden} Sekunden.',
  'UI-SPRACHE-ZU-GROSS': 'Die Aufnahme ist zu groß (höchstens {mb} MB).',
  'UI-SPRACHE-LEER': 'Die Aufnahme ist leer.',
  'UI-SPRACHE-FORMAT': 'Diese Aufnahme können wir nicht verarbeiten.',
  'UI-SPRACHE-NICHT-MOEGLICH': 'Sprachnachrichten sind gerade nicht möglich.',
  'UI-SPRACHE-MIKRO-ABGELEHNT': 'Das Mikrofon ist gesperrt. Erlaube es in den Einstellungen deines Browsers für diese Seite.',
  'UI-SPRACHE-MIKRO-FEHLT': 'Kein Mikrofon gefunden.',
  'UI-SPRACHE-HTTPS': 'Aufnahmen gehen nur über eine sichere Verbindung (https).',
  'UI-SPRACHE-BROWSER': 'Dieser Browser kann keine Aufnahmen machen.',
  'UI-SPRACHE-TEMPO': 'Tempo {tempo}',
  'UI-EINST-SPRACHE': 'Sprachnachrichten empfangen',
  'UI-EINST-SPRACHE-ERKL': 'Aus: Niemand kann dir Sprachnachrichten schicken. Das gilt auch in Cruizy Date.',

  # ───── #30 Gesprächsstarter ─────
  'UI-STARTER-TITEL': 'Ideen für den Anfang',
  'UI-STARTER-ANDERE': 'Andere Vorschläge',
  'UI-EINST-STARTER': 'Gesprächsstarter anzeigen',
  'UI-EINST-STARTER-ERKL': 'In neuen Chats schlagen wir dir ein paar Einstiege vor — aus dem, was im Profil der anderen Person steht. Nichts davon verlässt unseren Server.',

  # ───── #24 Antwortquote ─────
  'UI-AQ-INFO-TITEL': 'Was bedeutet das?',
  'UI-AQ-INFO-1': 'Das zeigt, wie zuverlässig jemand auf erste Nachrichten reagiert.',
  'UI-AQ-INFO-2-TITEL': 'So wird’s berechnet:',
  'UI-AQ-INFO-2': 'Wir schauen auf die letzten {tage} Tage. Als Antwort zählt jede Reaktion innerhalb von 3 Tagen, auch eine freundliche Absage.',
  'UI-AQ-INFO-3-TITEL': 'Kein Abzeichen?',
  'UI-AQ-INFO-3': 'Das heißt nicht, dass jemand nicht antwortet. Vielleicht ist er neu oder bekommt gerade wenige Nachrichten.',
  'UI-AQ-EIGEN': 'Deine Antwortquote: {prozent} % · {stufe}',
  'UI-AQ-EIGEN-OHNE-STUFE': 'Deine Antwortquote: {prozent} %',
  'UI-AQ-EIGEN-ERKL': 'Die Quote zählt, wie oft du in den letzten {tage} Tagen innerhalb von 3 Tagen auf neue Nachrichten reagiert hast.',
  'UI-AQ-TIPP': 'Tipp: Kein Interesse? Mit „Absagen“ antwortest du mit einem Tipp freundlich, und das zählt als Antwort.',
  'UI-AQ-NOCH-KEINE': 'Deine Antwortquote: Sobald du genug Nachrichten bekommen hast, siehst du hier deine Quote.',
  'UI-AQ-FORTSCHRITT': '{zahl} von {min} Unterhaltungen gezählt',

  # ───── #29 Vollständigkeit ─────
  'UI-VOLL-TITEL': 'Dein Profil ist zu {prozent} % fertig',
  'UI-VOLL-FERTIG': 'Dein Profil ist komplett!',
  'UI-VOLL-HINWEIS': 'Dein Profil ist erst zu {prozent} % fertig. Mit ein paar Angaben mehr bekommst du deutlich mehr Nachrichten.',
  'UI-VOLL-JETZT': 'Jetzt ergänzen',
  'UI-VOLL-TIPP-PROFILBILD': 'Lade ein Profilbild hoch – Profile mit Bild bekommen deutlich mehr Nachrichten.',
  'UI-VOLL-TIPP-DREI-FOTOS': 'Füg noch {zahl} Fotos hinzu.',
  'UI-VOLL-TIPP-DREI-FOTOS-1': 'Füg noch ein Foto hinzu.',
  'UI-VOLL-TIPP-BIO': 'Schreib ein paar Sätze über dich.',
  'UI-VOLL-TIPP-BASIS': 'Ergänze Alter, Größe, Gewicht und Körpertyp.',
  'UI-VOLL-TIPP-FOTO-ECHT': 'Lass dein Foto verifizieren – das schafft Vertrauen.',
  'UI-VOLL-TIPP-INTERESSEN': 'Wähle ein paar Interessen aus.',
  'UI-VOLL-TIPP-ABSICHT': 'Setz eine Absicht – dann wissen andere, was du gerade suchst.',

  # ───── #27 Profilbesucher ─────
  'UI-BESUCHER': 'Profilbesucher',
  'UI-BESUCHER-ANZAHL': '{zahl} Besucher in den letzten {tage} Tagen',
  'UI-BESUCHER-NEU': '{zahl} neu',
  'UI-BESUCHER-KEINE': 'In den letzten {tage} Tagen hat niemand dein Profil geöffnet.',
  'UI-BESUCHER-PREMIUM': 'Wer dein Profil angesehen hat, siehst du mit PLUS.',
  'UI-BESUCHER-PREMIUM-KNOPF': 'PLUS ansehen',
  'UI-BESUCHER-HEUTE': 'heute',
  'UI-BESUCHER-GESTERN': 'gestern',
  'UI-BESUCHER-WOCHE': 'diese Woche',
  'UI-BESUCHER-FRUEHER': 'früher',
  'UI-BESUCHER-UNSICHTBAR': 'Unsichtbar stöbern',
  'UI-BESUCHER-UNSICHTBAR-ERKL': 'Deine Besuche werden nicht gespeichert. Andere sehen nicht, dass du ihr Profil angesehen hast.',
  'UI-BESUCHER-UNSICHTBAR-PLUS': 'Nur mit PLUS.',
  'UI-ABO-TEST': 'PLUS im Testbetrieb 7 Tage ausprobieren',
  'UI-ABO-TEST-AKTIV': 'PLUS ist aktiv bis {datum}.',
  'UI-ABO-TEST-BEENDEN': 'PLUS beenden',

  # ───── #25 Gesundheit und Tests ─────
  'UI-TEST-BEREICH': 'Gesundheit & Tests',
  'UI-TEST-SCHALTER': 'Erinnere mich an einen Test',
  'UI-TEST-SCHALTER-ERKL': 'Auf sexuell übertragbare Infektionen. Freiwillig, nur für dich sichtbar, nie im Profil.',
  'UI-TEST-INTERVALL': 'Wie oft?',
  'UI-TEST-MONATE-1': 'jeden Monat',
  'UI-TEST-MONATE-3': 'alle 3 Monate',
  'UI-TEST-MONATE-6': 'alle 6 Monate',
  'UI-TEST-EINWILLIGUNG': 'Ich willige ein, dass Cruizy mein Erinnerungsintervall und das Datum der nächsten Erinnerung speichert, um mich zu erinnern. Diese Angaben sind nur für mich sichtbar, werden nicht im Profil angezeigt und nie weitergegeben. Ich kann das jederzeit ausschalten, dann werden die Daten gelöscht.',
  'UI-TEST-AKTIVIEREN': 'Erinnerung einschalten',
  'UI-TEST-NAECHSTE': 'Nächste Erinnerung: {datum}',
  'UI-TEST-GERADE': 'Ich war gerade testen',
  'UI-TEST-KANAL-PUSH': 'Per Push-Mitteilung',
  'UI-TEST-KANAL-APP': 'Als Hinweis in der App',
  'UI-TEST-KANAL': 'Wähle mindestens einen Weg.',
  'UI-TEST-PUSH': 'Du hast eine Erinnerung.',
  'UI-TEST-TITEL': 'Zeit für deinen Check!',
  'UI-TEST-TEXT': 'Regelmäßig testen schützt dich und andere.',
  'UI-TEST-TESTSTELLEN': 'Teststellen finden',
  'UI-TEST-ERLEDIGT': 'Erledigt',
  'UI-TEST-WOCHE': 'In einer Woche erinnern',
  'UI-TEST-AUS': 'Erinnerung ausschalten',
  'UI-TEST-AUS-FERTIG': 'Ausgeschaltet. Deine Angaben sind gelöscht.',
  'UI-TEST-DATEN': 'Gespeichert sind nur: Intervall, Datum der nächsten Erinnerung, Zeitpunkt deiner Einwilligung.',

  # ───── #18 Travel (Grundlage für das Raster) ─────
  'UI-TRAVEL-BEENDEN': 'Zurück zu meinem Ort',
  'UI-TRAVEL-BALD-REIHE': 'Bald in der Gegend',
  'UI-TRAVEL-BALD-KURZ': 'Bald in {ort}',
  'UI-TRAVEL-TITEL': 'Travel & Reisen',
  'UI-TRAVEL-MODUS': 'Travel-Modus',
  'UI-TRAVEL-MODUS-ERKL': 'Stöbere an einem anderen Ort und schreib Leuten dort. Sie sehen, wie weit du wirklich weg bist — und ein Reise-Zeichen. So wird niemand getäuscht.',
  'UI-TRAVEL-AKTIV': 'Du stöberst gerade in {ort}.',
  'UI-TRAVEL-STARTEN': 'Hier stöbern',
  'UI-TRAVEL-ORT': 'Ort suchen',
  'UI-TRAVEL-ORT-HINWEIS': 'Nur ein Dorf, eine Stadt oder ein Stadtteil — keine Region wie „Bayern“. Sonst können wir dich dort nicht als „bald in der Gegend“ zeigen.',
  'UI-TRAVEL-ZU-GROB': '„{ort}“ ist zu grob. Gib ein Dorf, eine Stadt oder einen Stadtteil ein.',
  'UI-TRAVEL-KEIN-ORT': 'Keinen passenden Ort gefunden. Versuch es mit der nächsten größeren Stadt.',
  'UI-TRAVEL-ORT-FEHLT': 'Diesen Ort kennen wir nicht.',
  'UI-TRAVEL-ABO': 'Travel gibt es mit PLUS.',
  'UI-TRAVEL-STOEBERT': 'stöbert gerade in {ort}',
  'UI-TRAVEL-ZEICHEN-AUTO': 'unterwegs',
  'UI-TRAVEL-ZEICHEN-FLUG': 'auf Reisen',
  'UI-VERSCHIEBEN': 'Punkt verschieben',
  'UI-VERSCHIEBEN-ERKL': 'Setz deinen Punkt bis zu {km} km von dort weg, wo du bist. Andere sehen Entfernungen von dort aus und „ungefährer Ort“.',
  'UI-VERSCHIEBEN-RICHTUNG': 'Richtung',
  'UI-VERSCHIEBEN-WEITE': 'Wie weit: {km} km',
  'UI-VERSCHIEBEN-SETZEN': 'Punkt setzen',
  'UI-VERSCHIEBEN-AKTIV': 'Dein Punkt ist verschoben.',
  'UI-VERSCHIEBEN-ZURUECK': 'Zurück auf meinen Ort',
  'UI-VERSCHIEBEN-ZU-WEIT': 'Höchstens {km} km. Für weiter weg gibt es den Travel-Modus.',
  'UI-VERSCHIEBEN-OHNE-ORT': 'Dafür braucht die App deinen Standort.',
  'UI-RICHTUNG-N': 'Nord', 'UI-RICHTUNG-NO': 'Nordost', 'UI-RICHTUNG-O': 'Ost', 'UI-RICHTUNG-SO': 'Südost',
  'UI-RICHTUNG-S': 'Süd', 'UI-RICHTUNG-SW': 'Südwest', 'UI-RICHTUNG-W': 'West', 'UI-RICHTUNG-NW': 'Nordwest',
  'UI-REISEN': 'Meine Reisen',
  'UI-REISEN-ERKL': 'Trag ein, wann du wo bist. Ab {tage} Tagen vor der Anreise erscheinst du dort unter „Bald in der Gegend“ — mit deiner echten Entfernung.',
  'UI-REISEN-NEU': 'Reise eintragen',
  'UI-REISEN-VON': 'Anreise',
  'UI-REISEN-BIS': 'Abreise',
  'UI-REISEN-OEFFENTLICH': 'Im Profil zeigen',
  'UI-REISEN-OEFFENTLICH-ERKL': 'Aus: Die Reise bleibt nur für dich, du erscheinst dort nicht als „bald in der Gegend“.',
  'UI-REISEN-LEER': 'Keine Reisen eingetragen.',
  'UI-REISEN-MAX': 'Höchstens {max} Reisen.',
  'UI-REISE-DATUM': 'Bitte prüf die Daten.',
  'UI-REISE-ZU-LANG': 'Eine Reise dauert höchstens {tage} Tage.',
  'UI-REISE-ZEILE': '{ort} · {von}–{bis}',
  'UI-PROFIL-REISEN': 'Reisen',
  'UI-GEONAMES': 'Ortsdaten: GeoNames (CC BY 4.0)',

  # ───── #16 Veranstaltungen (Server) ─────
  'UI-VA-EIGENE': 'Das ist deine eigene Veranstaltung.',
  'UI-VA-ABGELEHNT': 'Der Veranstalter hat deine Anfrage nicht angenommen.',
  'UI-VA-VOLL': 'Leider ausgebucht — es gibt keine freien Plätze mehr.',
  'UI-VA-FRIST-VORBEI': 'Die Absagefrist ist vorbei. Schreib dem Veranstalter, wenn du doch nicht kommen kannst.',
  'UI-VA-BEGINN-VORBEI': 'Der Beginn liegt in der Vergangenheit.',
  'UI-VA-ZU-WEIT': 'Veranstaltungen gehen höchstens {monate} Monate im Voraus.',
  'UI-VA-ENDE': 'Das Ende muss nach dem Beginn liegen.',
  'UI-VA-ZU-LANG': 'Eine Veranstaltung dauert höchstens 14 Tage.',
  'UI-VA-TEXT-LANG': 'Die Beschreibung darf höchstens {zeichen} Zeichen haben.',
  'UI-VA-FRIST-LANG': 'Die Absagefrist darf höchstens {std} Stunden betragen.',
  'UI-VA-ORT-FEHLT': 'Bitte wähl einen Ort.',
  'UI-VA-PIN-WEIT': 'Die Stecknadel liegt zu weit vom gewählten Ort entfernt.',
  'UI-VA-SCHON-BEANTRAGT': 'Du hast die Verifizierung schon beantragt.',
  'UI-VA-EINREICHUNGEN-MAX': 'Du hast schon {max} Veranstaltungen in Prüfung. Warte bitte, bis das Team entschieden hat.',
  'UI-VA-NICHT-AENDERBAR': 'Abgesagte oder vergangene Veranstaltungen lassen sich nicht mehr ändern.',
  'UI-VA-ERST-ABSAGEN': 'Sag die Veranstaltung zuerst ab — die Gäste sollen es erfahren.',
  'UI-VA-BILDER-MAX': 'Höchstens {max} Bilder je Veranstaltung.',
  'UI-VA-CHAT-ZU': 'Dieser Chat ist geschlossen.',
  'UI-VA-N-ANFRAGE-TITEL': 'Neue Anfrage für deine Veranstaltung',
  'UI-VA-N-ANFRAGE': 'Jemand möchte zu „{titel}“ kommen. Nimm die Anfrage in deiner Gästeliste an oder lehne sie ab.',
  'UI-VA-N-ANGENOMMEN-TITEL': 'Du bist dabei',
  'UI-VA-N-ANGENOMMEN': 'Der Veranstalter hat dich für „{titel}“ angenommen. Bei Fragen kannst du ihm jetzt schreiben.',
  'UI-VA-N-ABGELEHNT-TITEL': 'Anfrage nicht angenommen',
  'UI-VA-N-ABGELEHNT': 'Für „{titel}“ hat es diesmal nicht geklappt.',
  'UI-VA-N-ABGESAGT-TITEL': 'Veranstaltung abgesagt',
  'UI-VA-N-ABGESAGT': '„{titel}“ findet nicht statt.',
  'UI-VA-N-FREIGEGEBEN-TITEL': 'Veranstaltung freigegeben',
  'UI-VA-N-FREIGEGEBEN': '„{titel}“ ist jetzt in „Heute“ zu sehen.',
  'UI-VA-N-NICHT-FREIGEGEBEN-TITEL': 'Veranstaltung nicht freigegeben',
  'UI-VA-N-NICHT-FREIGEGEBEN': '„{titel}“ können wir so nicht veröffentlichen. {grund}',
  'UI-VA-N-VERIFIZIERT-TITEL': 'Du bist als Veranstalter verifiziert',
  'UI-VA-N-VERIFIZIERT': 'Deine Veranstaltungen erscheinen ab jetzt ohne Wartezeit in „Heute“ — mit dem Zeichen „verifiziert“.',
  'UI-VA-N-NICHT-VERIFIZIERT-TITEL': 'Verifizierung als Veranstalter',
  'UI-VA-N-NICHT-VERIFIZIERT': 'Wir konnten dich (noch) nicht als Veranstalter verifizieren. {grund}',
  'UI-MOD-NUR-EIGENE': 'Empfehlen lassen sich nur eigene Veranstaltungen von Cruizy.',

  # ───── #15 Heute ─────
  'UI-HEUTE-ENTDECKEN': 'Entdecken',
  'UI-HEUTE-HEUTE': 'Heute',
  'UI-HEUTE-MORGEN': 'Morgen',
  'UI-HEUTE-WANN-ALLE': 'Alle Termine',
  'UI-HEUTE-WANN-HEUTE': 'Heute',
  'UI-HEUTE-WANN-MORGEN': 'Morgen',
  'UI-HEUTE-WANN-WOCHENENDE': 'Wochenende',
  'UI-HEUTE-WANN-7TAGE': '7 Tage',
  'UI-HEUTE-WANN-30TAGE': '30 Tage',
  'UI-HEUTE-UMKREIS': 'Umkreis',
  'UI-HEUTE-UMKREIS-ERKL': 'Wie weit darf es sein? Gemessen von deinem ungefähren Standort — oder vom Ort, an dem du gerade per Travel stöberst.',
  'UI-HEUTE-UMKREIS-GROESSER': 'Umkreis vergrößern',
  'UI-HEUTE-DACH': 'DACH',
  'UI-HEUTE-ALLE-KATEGORIEN': 'Alle Kategorien',
  'UI-HEUTE-KATEGORIEN-N': '{zahl} Kategorien',
  'UI-HEUTE-SORTIERUNG': 'Sortierung wechseln',
  'UI-HEUTE-BALD': 'Bald zuerst',
  'UI-HEUTE-NAH': 'Nah zuerst',
  'UI-HEUTE-LEER': 'Hier ist gerade nichts eingetragen. Versuch einen größeren Umkreis oder weniger Filter.',
  'UI-HEUTE-FILTER-WEG': 'Filter zurücksetzen',
  'UI-HEUTE-OHNE-ORT': 'Ohne Standort zeigen wir Veranstaltungen ohne Entfernung.',
  'UI-HEUTE-ORT-WAEHLEN': 'Ort wählen',
  'UI-HEUTE-TRAVEL': 'Du stöberst gerade per Travel — Entfernungen gelten ab dort.',

  # ───── #17 Karte ─────
  'UI-KARTE-ANZAHL': '{zahl} Veranstaltungen im Ausschnitt',
  'UI-KARTE-LAEDT': 'Lädt …',
  'UI-KARTE-GRUPPE': '{zahl} Veranstaltungen — hineinzoomen',
  'UI-KARTE-ZU-MIR': 'Zu meinem Standort',
  'UI-KARTE-GENAU': 'genauer Ort',
  'UI-KARTE-UNGEFAEHR': 'ungefähre Gegend',

  # ───── #16 Veranstaltungen (App) ─────
  'UI-VA-EINTRAGEN': 'Veranstaltung eintragen',
  'UI-VA-EMPFOHLEN': 'Empfohlen von Cruizy',
  'UI-VA-VON': 'von {name}',
  'UI-VA-VERIFIZIERT': 'verifizierter Veranstalter',
  'UI-VA-EINGEREICHT': 'geprüft vom Cruizy-Team',
  'UI-VA-DEINE': 'Deine',
  'UI-VA-DEINE-ERKL': 'Das ist deine Veranstaltung.',
  'UI-VA-DABEI': 'Dabei',
  'UI-VA-DU-BIST-DABEI': 'Du bist dabei',
  'UI-VA-ANGEFRAGT': 'Angefragt',
  'UI-VA-AUSGEBUCHT': 'Ausgebucht',
  'UI-VA-PLAETZE-FREI': 'noch {frei} von {gesamt} Plätzen frei',
  'UI-VA-KATEGORIEN': 'Kategorien',
  'UI-VA-DETAILS': 'Zur Veranstaltung',
  'UI-VA-LAGE-UNGEFAEHR': 'Auf der Karte nur ungefähr — die genaue Adresse sehen angenommene Gäste.',
  'UI-VA-ADRESSE-NACH-ZUSAGE': 'Adresse nach deiner Zusage',
  'UI-VA-AUF-KARTE': 'Auf der Karte zeigen',
  'UI-VA-ABSAGEN-BIS': 'Absagen bis {zeit}',
  'UI-VA-ANNAHME-ERKL': 'Der Veranstalter nimmt die Gäste selbst an. Du bekommst Bescheid.',
  'UI-VA-CHAT-MIT-VERANSTALTER': 'Dem Veranstalter schreiben',
  'UI-VA-ANFRAGEN': 'Teilnahme anfragen',
  'UI-VA-ANFRAGE-GESENDET': 'Anfrage gesendet. Du bekommst Bescheid.',
  'UI-VA-ZUGESAGT': 'Du bist dabei!',
  'UI-VA-ANFRAGE-OFFEN': 'Anfrage offen',
  'UI-VA-ANFRAGE-ZURUECK': 'Zurückziehen',
  'UI-VA-ABSAGEN': 'Absagen',
  'UI-VA-ABSAGEN-FRAGE': 'Wirklich absagen? Dein Platz wird für andere frei.',
  'UI-VA-ABBRECHEN': 'Abbrechen',
  'UI-VA-IN-PRUEFUNG': 'In Prüfung — das Cruizy-Team schaut sich deine Einreichung an. Erst danach ist sie für andere sichtbar.',
  'UI-VA-NICHT-FREIGEGEBEN': 'Diese Einreichung wurde nicht freigegeben.',
  'UI-VA-VERWALTEN': 'Verwalten',
  'UI-VA-HAFTUNG': 'Veranstaltungen werden von den jeweiligen Veranstaltern eingestellt. Cruizy organisiert sie nicht, ist nicht Vertragspartner und übernimmt keine Haftung für Durchführung, Angaben, Preise oder Sicherheit vor Ort. Bei Problemen: melden.',
  'UI-VA-HAFTUNG-VERANSTALTER': 'Du bist Veranstalter und verantwortlich für die Veranstaltung, deine Angaben und die Einhaltung der Gesetze (u. a. Jugendschutz, Hausrecht, Lärmschutz). Cruizy stellt nur die Fläche bereit. Keine Privatadressen anderer Personen, keine Versprechen, die du nicht halten kannst.',
  'UI-VA-DU-VERANSTALTEST': 'Du veranstaltest etwas?',
  'UI-VA-DU-VERANSTALTEST-ERKL': 'Party, Konzert, Stammtisch oder Brunch — trag es ein.',
  'UI-VA-INFO-TITEL': 'Veranstalter bei Cruizy',
  'UI-VA-INFO-1': 'Veranstaltungen direkt veröffentlichen können nur Konten, die als Veranstalter verifiziert sind — etwa Bars, Clubs, Restaurants, Konzerthäuser, Partyreihen oder Vereine.',
  'UI-VA-INFO-2': 'Ohne Verifizierung kannst du eine Veranstaltung einreichen. Das Cruizy-Team prüft sie und gibt sie im Einzelfall frei — auch private Partys.',
  'UI-VA-INFO-SCHRITT-1': 'Verifizierung beantragen: Name, Art, Stadt, Website und eine Mail-Adresse, unter der wir dich erreichen.',
  'UI-VA-INFO-SCHRITT-2': 'Wir prüfen die Angaben — meist über Website, Impressum oder eine Rückfrage per Mail.',
  'UI-VA-INFO-SCHRITT-3': 'Danach erscheinen deine Veranstaltungen sofort und mit dem Zeichen „verifiziert“.',
  'UI-VA-INFO-3': 'Voraussetzung ist ein Konto mit Altersprüfung. Verifizierte Veranstaltungen prüft das Team stichprobenartig nach; die Verifizierung lässt sich bei Verstößen entziehen.',
  'UI-VA-VERIFIZIERUNG-BEANTRAGEN': 'Verifizierung beantragen',
  'UI-VA-WIE': 'Wie geht das?',
  'UI-VA-BEREICH': 'Veranstalter',
  'UI-VA-BEREICH-ERKL': 'Veranstaltungen eintragen, Gäste, Verifizierung',
  'UI-VA-VERIFIZIERT-ERKL': 'Du bist als Veranstalter verifiziert. Deine Veranstaltungen erscheinen sofort.',
  'UI-VA-BEANTRAGT': 'Verifizierung beantragt',
  'UI-VA-BEANTRAGT-ERKL': 'Wir melden uns. Bis dahin kannst du bis zu {max} Veranstaltungen zur Prüfung einreichen.',
  'UI-VA-NICHT-VERIFIZIERT': 'Noch nicht als Veranstalter verifiziert',
  'UI-VA-NICHT-VERIFIZIERT-ERKL': 'Du kannst bis zu {max} Veranstaltungen gleichzeitig zur Prüfung einreichen — oder dich als Veranstalter verifizieren lassen.',
  'UI-VA-NEU': 'Neue Veranstaltung',
  'UI-VA-EINREICHEN': 'Veranstaltung einreichen',
  'UI-VA-VEROEFFENTLICHEN': 'Veröffentlichen',
  'UI-VA-EINREICHUNGEN-OFFEN': '{zahl} von {max} Einreichungen in Prüfung',
  'UI-VA-EINREICHUNG-HINWEIS': 'Du bist (noch) nicht als Veranstalter verifiziert. Deine Veranstaltung geht zuerst an das Cruizy-Team und ist erst nach der Freigabe sichtbar.',
  'UI-VA-MEINE': 'Meine Veranstaltungen',
  'UI-VA-MEINE-LEER': 'Noch keine Veranstaltungen.',
  'UI-VA-STATUS-PRUEFUNG': 'In Prüfung',
  'UI-VA-STATUS-SICHTBAR': 'Sichtbar',
  'UI-VA-STATUS-ABGELEHNT': 'Nicht freigegeben',
  'UI-VA-STATUS-ABGESAGT': 'Abgesagt',
  'UI-VA-STATUS-VORBEI': 'Vorbei',
  'UI-VA-ZAHL-DABEI': '{zahl} dabei',
  'UI-VA-ZAHL-ANFRAGEN': '{zahl} Anfragen',
  'UI-VA-ZAHL-ABGESAGT': '{zahl} abgesagt',
  'UI-VA-FORM-ERKL': 'Diese Angaben sieht nur das Cruizy-Team. Öffentlich erscheint nur der Name.',
  'UI-VA-FORM-NAME': 'Name (Bar, Club, Partyreihe …)',
  'UI-VA-FORM-ART': 'Art',
  'UI-VA-FORM-STADT': 'Stadt',
  'UI-VA-FORM-WEBSITE': 'Website (freiwillig)',
  'UI-VA-FORM-WEBSITE-ERKL': 'Hilft beim Prüfen — etwa über das Impressum.',
  'UI-VA-FORM-MAIL': 'Mail-Adresse für Rückfragen',
  'UI-VA-FORM-MAIL-ERKL': 'Am besten eine Adresse auf der Domain deiner Website.',
  'UI-VA-FORM-NOTIZ': 'Was sollen wir wissen? (freiwillig)',
  'UI-VA-FORM-NOTIZ-ERKL': 'Zum Beispiel: seit wann es euch gibt, wo man euch findet.',
  'UI-VA-BEARBEITEN': 'Bearbeiten',
  'UI-VA-F-TITEL': 'Titel',
  'UI-VA-F-KATEGORIEN': 'Kategorien (bis zu {max})',
  'UI-VA-F-BEGINN': 'Beginn',
  'UI-VA-F-ENDE': 'Ende',
  'UI-VA-F-ZEIT-ERKL': 'Bis zu {monate} Monate im Voraus.',
  'UI-VA-F-ORT': 'Ort',
  'UI-VA-F-ORT-BISHER': 'Bisher: {ort}. Wähl den Ort zum Speichern noch einmal.',
  'UI-VA-ORT-NEU-WAEHLEN': 'Bitte wähl den Ort noch einmal.',
  'UI-VA-F-OEFFENTLICH': 'Öffentlicher Veranstaltungsort',
  'UI-VA-F-OEFFENTLICH-ERKL': 'Club, Bar, Konzerthaus, Park … Dann stehen Adresse und genauer Punkt für alle sichtbar. Bei privaten Orten: aus lassen.',
  'UI-VA-F-ADRESSE': 'Adresse',
  'UI-VA-F-ADRESSE-OEFFENTLICH': 'Für alle sichtbar.',
  'UI-VA-F-ADRESSE-PRIVAT': 'Sehen nur Gäste, die dabei sind. Auf der Karte steht nur die ungefähre Gegend.',
  'UI-VA-PIN': 'Genauer Punkt auf der Karte',
  'UI-VA-PIN-ERKL': 'Tipp auf die Karte, um den Eingang zu markieren (freiwillig).',
  'UI-VA-PIN-GESETZT': 'Punkt gesetzt — tipp erneut, um ihn zu verschieben.',
  'UI-VA-F-BESCHREIBUNG': 'Beschreibung',
  'UI-VA-F-BESCHREIBUNG-ERKL': 'Was erwartet die Gäste? Musik, Ablauf, Einlass, Awareness …',
  'UI-VA-F-BILDER': 'Bilder (bis zu {max})',
  'UI-VA-F-BILDER-ERKL': 'Flyer, Location, Stimmung. Keine erkennbaren Personen ohne deren Einverständnis. Alle Metadaten werden entfernt.',
  'UI-VA-F-GAESTE': 'Gäste',
  'UI-VA-F-PLAETZE': 'Plätze (freiwillig)',
  'UI-VA-F-PLAETZE-ERKL': 'Wie viele Gäste passen? Die Zahl der freien Plätze wird angezeigt.',
  'UI-VA-F-ANNAHME': 'Gäste selbst annehmen',
  'UI-VA-F-ANNAHME-ERKL': 'Aus: Zusagen gelten sofort. An: Gäste fragen an, du nimmst an oder lehnst ab.',
  'UI-VA-F-FRIST': 'Absagen möglich bis',
  'UI-VA-F-FRIST-KEINE': 'bis zum Beginn',
  'UI-VA-F-FRIST-STD': '{std} Std. vorher',
  'UI-VA-F-FRIST-TAGE': '{tage} Tage vorher',
  'UI-VA-F-FRIST-ERKL': 'Danach können angenommene Gäste nicht mehr selbst absagen, sondern nur dir schreiben.',
  'UI-VA-F-MEHR': 'Weitere Angaben',
  'UI-VA-F-PREIS': 'Eintritt (freiwillig)',
  'UI-VA-F-PREIS-BSP': 'z. B. 10 € Abendkasse, frei',
  'UI-VA-F-DRESSCODE': 'Dresscode (freiwillig)',
  'UI-VA-F-EINSTUFUNG': 'Einstufung',
  'UI-VA-F-EINSTUFUNG-GRUEN': 'Allgemein',
  'UI-VA-F-EINSTUFUNG-GELB': 'Erotik angedeutet',
  'UI-VA-F-EINSTUFUNG-ROT': 'Explizit — nur für Konten mit Altersprüfung sichtbar',
  'UI-VA-GESPEICHERT-SICHTBAR': 'Gespeichert — deine Veranstaltung ist sichtbar.',
  'UI-VA-GESPEICHERT-PRUEFUNG': 'Eingereicht — das Team prüft sie jetzt.',
  'UI-VA-VON-PLAETZEN': 'von {zahl} Plätzen',
  'UI-VA-ABGESAGT-N': 'Abgesagt',
  'UI-VA-TESTGAESTE': 'Davon {zahl} erfundene Testgäste (Testbetrieb).',
  'UI-VA-ANSEHEN': 'Ansehen',
  'UI-VA-GAESTE-LEER': 'Hier ist noch niemand.',
  'UI-VA-ABGELEHNT-KURZ': 'nicht angenommen',
  'UI-VA-ABLEHNEN': 'Nicht annehmen',
  'UI-VA-ANNEHMEN': 'Annehmen',
  'UI-VA-SCHREIBEN': 'Schreiben',
  'UI-VA-ABSAGEN-VERANSTALTUNG': 'Veranstaltung absagen',
  'UI-VA-ABSAGEN-VERANSTALTUNG-ERKL': 'Alle Gäste bekommen eine Mitteilung. Das lässt sich nicht rückgängig machen.',
  'UI-VA-ABSAGE-NOTIZ': 'Kurzer Hinweis für die Gäste (freiwillig)',
  'UI-VA-LOESCHEN': 'Einreichung löschen',
  'UI-VA-CHATS': 'Veranstaltungen',
  'UI-VA-CHATS-ERKL': 'Chats zwischen Veranstaltern und angenommenen Gästen — getrennt von deinen privaten Chats.',
  'UI-VA-CHATS-LEER': 'Noch keine Chats zu Veranstaltungen.',
  'UI-VA-ROLLE-GAST': 'Gast',
  'UI-VA-ROLLE-VERANSTALTER': 'Veranstalter',
  'UI-VA-CHAT-ERKL-VERANSTALTER': 'Chat mit einem angenommenen Gast deiner Veranstaltung.',
  'UI-VA-CHAT-ERKL-GAST': 'Fragen zur Veranstaltung? Hier schreibst du direkt dem Veranstalter.',

  # ───── #19 Cruizy Date (Server) ─────
  'UI-DATE-GESPERRT': 'Dein Zugang zu Cruizy Date ist gesperrt. Die Cruizy-Hauptseite kannst du weiterhin nutzen.',
  'UI-DATE-NUR-MITGLIEDER': 'Das siehst du nur mit freigeschaltetem Cruizy Date.',
  'UI-DATE-WARTELISTE': 'Wir starten Cruizy Date Stadt für Stadt. Du bist dabei, sobald es bei dir losgeht.',
  'UI-DATE-FOTOS-MAX': 'Höchstens {max} Fotos.',
  'UI-DATE-EINWILLIGUNG-NOETIG': 'Bitte stimm der Verarbeitung für die Gesichtsverifizierung zu.',
  'UI-DATE-VERIFIZIERUNG-NICHT-VERFUEGBAR': 'Die Gesichtsverifizierung ist gerade nicht verfügbar. Bitte versuch es später noch einmal.',
  'UI-DATE-POSE-ABGELAUFEN': 'Die Aufgabe ist abgelaufen. Hol dir eine neue Pose.',
  'UI-DATE-ERST-FOTOS': 'Lade zuerst deine Date-Fotos hoch — das erste wird mit dem Selfie abgeglichen.',
  'UI-DATE-INTERESSEN-ANZAHL': 'Wähl {min} bis {max} Interessen.',
  'UI-DATE-SUCHE-LANG': '„Was ich suche“ darf höchstens {zeichen} Zeichen haben.',
  'UI-DATE-PROMPTS-ANZAHL': 'Beantworte {min} bis {max} Fragen.',
  'UI-DATE-KOMMENTAR-LANG': 'Ein Kommentar darf höchstens {zeichen} Zeichen haben.',
  'UI-DATE-PREMIUM': 'Das gehört zu Premium.',
  'UI-DATE-ELEMENT-FEHLT': 'Das gibt es im Profil nicht mehr.',
  'UI-DATE-SCHON-GELIKT': 'Du hast diese Person schon gelikt.',
  'UI-DATE-NSFW-NEIN': 'Die andere Person empfängt in Date-Chats keine Bilder, die intime Inhalte zeigen könnten.',
  'UI-DATE-NSFW-EINMAL': 'Einmal-Bilder, die intime Inhalte zeigen könnten, gehen in Date-Chats erst, wenn die andere Person sie erlaubt hat.',
  'UI-DATE-N-MATCH-TITEL': 'Neues Match in Cruizy Date',
  'UI-DATE-N-MATCH': 'Ihr habt euch gegenseitig gelikt. Euer Chat liegt unter „Chats“ im Reiter „Date“.',
  'UI-DATE-N-MATCH-PUSH': 'Du hast ein neues Match.',
  'UI-DATE-N-GESPERRT-TITEL': 'Cruizy Date gesperrt',
  'UI-DATE-N-GESPERRT': 'Dein Zugang zu Cruizy Date wurde gesperrt, weil dein Verhalten nicht zu ernsthaftem Dating gepasst hat. Die Cruizy-Hauptseite kannst du weiterhin nutzen.',
  'UI-DATE-N-ENTSPERRT-TITEL': 'Cruizy Date wieder offen',
  'UI-DATE-N-ENTSPERRT': 'Dein Zugang zu Cruizy Date ist wieder freigeschaltet.',
  'UI-DATE-N-FOTO-ABGELEHNT-TITEL': 'Date-Foto nicht freigegeben',
  'UI-DATE-N-FOTO-ABGELEHNT': 'Ein Foto aus deinem Date-Profil passt nicht zu Date (Profile bleiben jugendfrei). Lade bitte ein anderes hoch.',
  'UI-MEL-DATE': 'Sucht nur Hookups / passt nicht zu Date',
  'UI-ENTSCHEIDUNG-DATE-VERSTOSS': 'Verstoß gegen den Date-Kodex',
  'UI-SYS-DATE-MATCH': 'Ihr habt euch in Cruizy Date gematcht.',
  'UI-SYS-DATE-MATCH-BESTEHEND': 'Ihr habt euch auch in Cruizy Date gematcht.',
  'UI-SYS-DATE-UNMATCH': 'Das Date-Match wurde aufgelöst.',
}

# Bestehende Texte, die sich durch die Issues ändern
ERSETZT = {
  'UI-FOTOS-MAX': 'Mehr als {max} Fotos gehen nicht.',
  'UI-ALBUM-MEINS': 'Private Alben',
}
